### ISSUE TITLE
[docs] theme docs rollout, continued

### ISSUE THREAD

**Issue by marcysutton** [gatsbyjs/gatsby#15382]
## Summary

In the rollout of themes, here are some recommendations to make to make sure the docs are intuitive and cover common questions and use cases.

- [ ] Add a reference guide on [Component Shadowing](https://www.gatsbyjs.org/blog/2019-04-29-component-shadowing/) to [/docs/themes](https://www.gatsbyjs.org/docs/themes/) (#15745)
- [x] Add a reference guide on Using [Theme UI with Gatsby](https://theme-ui.com/gatsby-plugin/) in the same section (#15764)
- [x] Put Theme/Component Shadowing API docs in the [Gatsby API](https://www.gatsbyjs.org/docs/api-reference/) section 
    - "Plugin and Theme APIs" maybe? We intentionally kept Themes outside of Plugins for discoverability even though themes are technically plugins. But it could be useful in the context of API-specific docs
- [x] The Building Themes docs will be important to add as well.
   - [x] Build a theme tutorial (#14099)
   - [x] Build a theme guide (#15641)
   - [x] Include a link to the [Accessibility Testing guide](https://www.gatsbyjs.org/docs/making-your-site-accessible#how-to-improve-accessibility) to help everyone building themes, including those entering the [Theme Jam Contest](https://themejam.gatsbyjs.org) (#16100)

Template for reference guides: https://www.gatsbyjs.org/contributing/docs-templates/#reference-guides

cc @amberleyromo @ChristopherBiscardi @jxnblk

**Comment by marcysutton** [comment]
I should add there are starter and theme recipes related to this rollout too, but they are tracked in separate issues! 
- https://github.com/gatsbyjs/gatsby/issues/14943
- https://github.com/gatsbyjs/gatsby/issues/14944

**Comment by marisamorby** [comment]
Based on 7/11 conversation: create issues for the first three items:
* Add a reference guide on Component Shadowing to /docs/themes
* Add a reference guide on Using Theme UI with Gatsby in the same section
* Put Theme/Component Shadowing API docs in the Gatsby API section

cc: @amberleyromo

**Comment by lannonbr** [comment]
As of 4 days ago all of the TODOs on this issue were completed, so this is finished
