### ISSUE TITLE
Structured logging 

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#17109]
### To Do 
- [x] Always fail on panic 
- [x] Write test suite 
- [x] Add normalised date string (`timestamp`) for log actions
- [x] figure out reliable way to determine if gatsby version that is installed support ipc communication
- [x] Smarter Debounce status changes (for now hard coded 1s debounce)
- [x] Figure out a way to catch all unhandled thrown exceptions and report them 
	- [x] Set status to failure
- [x] Wait on pending jobs for set status 
	- [x] Enable ability to hide activities so that some activities while being 
tracked for setting status will not be visible to the user
- [x] Webpack bundle failing is showing up as success
- [x] Mark some activities as hidden 
- [x] Pass through error code in premature end handler in signal exit 
- [x] Move types of activities to constants 
- [x] Add stack for structured error log
- [x] Restore in-browser error overlay for query extraction errors (@pieh)
- [x] Restore query running split (first static queries, then webpack build, then page queries) in `gatsby build` (@pieh)
- [x] Handle webpack warnings (right now we only handle displaying/emitting webpack errors)
- [x] Figure out why https://circleci.com/gh/gatsbyjs/gatsby/209016?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link happened 
- [x] Ensure all GraphQL extraction errors are emitted as structured errors (@pieh)
- [x] Remove VERSION ipc message - this is not used by anyone
- [x] Fix hot reloading test
- [x] Get rid of redundant constants
- [x] Figure out console over rides and make sure the correct level of the action is reported (error, warn etc) https://github.com/gatsbyjs/gatsby/issues/14834 (@sidharthachatterjee)
- [x] Check if telemetry analytics is all good (@pieh)
- [x] Streamline and combine `LOG`, `SUCCESS` and `INFO` levels (@sidharthachatterjee)
- [x] Add more integration tests that verify shape of all messages in protocol 
- [ ] ~Document reporter~ https://github.com/gatsbyjs/gatsby/issues/15898
- [ ] ~Make API constant for progress and activity timer~ https://github.com/gatsbyjs/gatsby/issues/17421
- [ ] ~Ink uses store and needs to have special handling for hidden stuff~ https://github.com/gatsbyjs/gatsby/issues/17422
- [ ] ~Figure out how to ensure concurrent builds don't interfere with each other when running integration tests~ (we run them serially for now)
- [ ] ~Add a Gatsby CLI option to select a logger (JSON or regular)~ https://github.com/gatsbyjs/gatsby/issues/17836
- [ ] ~Do we handle spawned processes?~ 
- [ ] ~Some tools that currently depend on Gatsby log output _may_ break since we no longer print `DONE  Compiled successfully in 4333ms`~ 
- [ ] https://github.com/gatsbyjs/gatsby/issues/18383

**Comment by sidharthachatterjee** [comment]
> Perhaps just do that directly by creating new activities to combine the old ones? Not sure how a helper function would help?

Not sure yet but a helper function might be less destructive (we want to still keep the more granular activities for telemetry and open tracing)

**Comment by sidharthachatterjee** [comment]
Published in `gatsby@2.16.0` and `gatsby-cli@2.8.0`
