### ISSUE TITLE
v2 umbrella issue

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#1824]
>v2 you say? But we just released a v1???

Well… yes but we're on webpack 1 and webpack 3 is out and Babel 7 is almost out etc. so there's some breaking changes we need to make to upgrade so new major release it is!

The changes should be pretty minor for most sites. Unless you're directly modifying webpack/babel settings, nothing should change. Once it's out, you'll just need to upgrade Gatsby + any plugins you've added.

We'd love your help tackling the various TODOs. We're working on the [`v2` branch](https://github.com/gatsbyjs/gatsby/tree/v2) so jump in and start helping.

Check out the contributions docs if you're new to developing with Gatsby https://www.gatsbyjs.org/docs/how-to-contribute/

If there's not an issue already created for a TODO below, create one with any your ideas and ask for feedback/guidance.

## TODOs

- [ ] Ongoing task—keep v2 branch up-to-date with master
- [x] Upgrade to webpack 3 ([the initial PR](https://github.com/gatsbyjs/gatsby/pull/1637) only got it to webpack 2)
- [ ] meta — copy good ideas from CRA
- [x] add CRA's overlay
- [x] add CRA's eslint setup (the above two might be doable in v1 as well)
- [x] add CRA's local network address feature
- [ ] "Reduxify" the API for modifying Babel configs
- [ ] [Update Gatsby's caching setup for webpack 3](https://medium.com/webpack/predictable-long-term-caching-with-webpack-d3eee1d3fa31)
- [ ] Convert all node IDs generated by source/transformer plugins to use UUID v5 so people don't depend on them for anything
- [ ] Convert `pathContext` to `pageContext` https://github.com/gatsbyjs/gatsby/issues/1456
- [x] remove global CLI capability from gatsby package
- [ ] all APIs should require the full object. This is especially important for deleting things as if you're responding to events, once the object is deleted, you can't access the object other than if it's passed to the event.
- [ ] think more about bulk APIs e.g. `deleteNodes`. Is potential efficiency gains worth extra code complexity? Could just standardize on bulk api and remove single shot API.
- [ ] Use UUID version 5 for node IDs in source/transformer plugins #1853

Other breaking changes we should make? Add a comment!

**Comment by jquense** [comment]
maybe pass through the `graphql` in the plugin api to avoid some of the multiple instance issues?

**Comment by gagan0723** [comment]
Serve site over the network.

**Comment by KyleAMathews** [comment]
>Serve site over the network

@gagan0723 not sure what you mean here?

**Comment by KyleAMathews** [comment]
For service workers, there's gatsby-plugin-offline https://www.gatsbyjs.org/packages/gatsby-plugin-offline/

**Comment by gagan0723** [comment]
>Serve site over the network

@KyleAMathews What I mean is, is there a way to serve site on the local network so that it may be viewed on other devices connected to the same network.

**Comment by KyleAMathews** [comment]
Oh ok, so like Create React App, tell you the address you can use to access the site. No that is a great idea. Adding it.

**Comment by KyleAMathews** [comment]
Closing this in favor of #2641
