### ISSUE TITLE
Make JSDoc for API files translateable

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#18704]
## Summary

Much of the content of the [API section](https://www.gatsbyjs.org/docs/api-reference/) of the website is directly sourced from documentation through [Documentation.js](https://www.gatsbyjs.org/packages/gatsby-transformer-documentationjs). This content can't be as easily extracted for translation as markdown files or yaml strings, so we need to figure out a way to deal with them.

## Steps

* [ ] Convert API docs pages to MDX #19035
* [ ] Make API JSDocs more easily extractable for translation #19383
* [x] Figure out what to do with actions API and node-model #19382

**Comment by tesseralis** [comment]
Doing research, it seems like most of the API is documented in individual files:

* https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/api-node-docs.js
* https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/api-browser-docs.js

The only one that isn't is node-model: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/node-model.js

Given this, the process should be something like

* put these files in their own dedicated folder instead of just `utils`
* factor out "api-node-model-docs"
* extract these files into `gatsby-i18n-source`

**Comment by muescha** [comment]
- factor out "api-node-model-docs" -> #19027
