### ISSUE TITLE
☂️ [Umbrella Issue] Localize gatsbyjs.org

### ISSUE THREAD

**Issue by tesseralis** [gatsbyjs/gatsby#19351]
## Summary

This is an umbrella issue for all the steps necessary to get gatsbyjs.org localized.

### Motivation

See [the RFC](https://github.com/gatsbyjs/rfcs/blob/master/text/0010-gatsby-docs-localization.md) for details on the importance of this work.

### Site Integration

The following are issues related to getting the gatsby site up and running in a variety of languages.

* [ ] Make `gatsby-plugin-gatsby-api-calls` a standalone plugin #23928
* [ ] Convert gatsbyjs.org into a theme #23926

### Translation Repositories

These are issues related to translation repositories and automation to help maintainers manage their repos.

* [x] Script to create new repositories
* [x] Script to update the source repository ([gatsby-i18n-source](https://github.com/gatsbyjs/gatsby-i18n-source))
* [x] Add prettier + commit hook https://github.com/gatsbyjs/gatsby-i18n-source/pull/2
* [x] Normalize Spanish and Russian repositories #19359
* [x] Script to keep translation repositories up-to-date with source 
  * Issue: #21250 / PR: #21185
* [x] Run sync script automatically #21828
* [ ] Automated progress issues #19356
* [ ] Come up with concrete criteria for a "finished" translation
* [ ] Fix permissions issues for translation maintainers #19358
* [x] Figure out integration strategy for translation repos #20853 

### Site Integration (OUTDATED)

The following issues are outdated, since we are [changing our approach to separate sites per translation](https://github.com/gatsbyjs/gatsby/issues/19351#issuecomment-625518299).

~~These are issues related to actually integrating localization into gatsbyjs.org.~~

The following issues involve integrating localization to the site as a whole:

* [x] Change routing to support localization #17759
* [x] Pull in translation repos as sources #19353 
* [x] Make components used in MDX globally available #19036
* [x] Make the sidebar work with localized pages #20796
* [x] Make UI text translatable
  * Issue: #19102  / PR: #21633
* [x] Use `localized-link` for all links
  * Issue: #20797 / PR: #20820
* [ ] Make sidebar links localizable #20587
* [ ] Language selector dropdown #21746
* [ ] `/languages` page
  * Issue: #21750 / PR: #21882
* [ ] Make localized heading anchors work #20732
* [ ] Improve Lingui workflow #22673
* [x] Move localization path logic to a plugin #21538
* [x] Create localized versions of all site pages
  * Issue: #21105 / PR: #21632
* [ ] Decide what components need to be disabled for localized sites #21775 
 
The following issues involve some, but not all languages:

* [ ] Support right-to-left text #17774
* [ ] Support alternate fonts for different languages #20928

The following issues involve preparing specific pages of the site for localization:

* [x] Convert API docs pages to MDX
  * Issue: #19035 / PR: #20763
* [ ] Make API JSDocs more easily extractable for translation #19383
* [ ] Figure out what to do with remaining relative MDX imports #20795 
* [ ] Make the glossary more translate-able #20930
* [x] Convert events and stub-list pages to MDX #21259
* [x] Convert older files to use soft line wraps #20769 

The following issues are not as critical for the initial integration:

* [ ] Figure out how to translate site metadata #21383
* [ ] Update DocSearch to support multiple languages #20932 
* [ ] Translator credit #21706
* [ ] Keep track of which pages have been translated in frontmatter #21104
* [ ] Support "Last Updated" field for translated files #22553

**Comment by tesseralis** [comment]
Update: After extensive testing, we’ve come to the realization that our current approach (put all translations under the same site) is currently infeasible. We’ve decided to change approaches and build separate websites for each language. For example, instead of `gatsbyjs.org/ja`, the Japanese translation would be at `ja.gatsbyjs.org`.

The general approach is:

1. Port the `www` folder into a theme, and make the current `www` folder a skeleton that sets up English configuration for the theme.
2. Add this skeleton `www` implementation that uses the theme in each of the language repos through the sync process.
3. Set up builds for the different language sites on Gatsby Cloud.

For more information, please see this gist: https://gist.github.com/tesseralis/f7f5f7da2f7f6cf5c2fa6ee715b5ff6d

There shouldn’t be many changes to the way docs are translated; everything will still be under translation repos like `gatsby-es`. I’ll update this issue and post on the Discord if there are additional changes (for example, translating UI text).

The Gatsby team _is_ working on improvements to make the translation experience more streamlined. In the future, we would like to switch to a single-site approach, but for now our main goal is to unblock localized sites so that all our translators’ hard work can be published. When Gatsby does publish an official i18n approach, we can be be sure that our docs site will be one of the first to use it!

**Comment by dragoneena12** [comment]
@tesseralis Hi, is there any task about this issue I can work on?
