### ISSUE TITLE
[Umbrella Issue] ☂️- Improvements for Gatsby Contributors

### ISSUE THREAD

**Issue by blainekasten** [gatsbyjs/gatsby#19597]
## Summary

This umbrella feature is to collect information and begin a process to empower our contributors! 

### Motivation

We deeply care about the Gatsby community ❤️ and want to empower them to help shape Gatsby. As of today, there are a few things left to be desired when learning how to work in the Gatsby codebase and not everyone has the time it takes to get involved.

### Issues

- [ ] [Local setup](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/)
- [ ] [Repo size](https://github.com/gatsbyjs/gatsby/issues/13699)
- [ ] Contributor Confidence (tests, type system, etc)

**Comment by vladar** [comment]
WRT local setup: I think we should at least mention an option of using yarn workspace for a site as an alternative to `gatsby-dev-cli`

**Comment by moonmeister** [comment]
doing any dev work on the website is a serious resource hog, and time intensive process that needs addressing...

https://github.com/gatsbyjs/gatsby/issues/22649
