### ISSUE TITLE
Unexpected data mutation in plugins

### ISSUE THREAD

**Issue by vladar** [gatsbyjs/gatsby#19876]
Gatsby version 2.18.0 revealed problems in several plugins which mutate data after `createNode` call. When they do so - mutated fields are not registered by gatsby internal data tracking and are not added to the GraphQL schema.

After `gatsby 2.18.5` things work closer to how they did in `2.17.x` so those issues are hidden again. But they still exist and must be addressed in every affected plugin. Otherwise, various new features including incremental builds may break.

We should do an audit for data-mutation patterns in plugins, address them (for gatsby own plugins), and help authors of community plugins to fix them too. We should also ensure we don't encourage data mutation practice in our docs.

The list of plugins which are probably affected:

- [x] gatsby-remark-relative-images (#19748)
- [x] gatsby-source-airtable (already fixed)
- [x] gatsby-plugin-remote-images (graysonhicks/gatsby-plugin-remote-images#28)
- [x] gatsby-source-contentful (#19716)

**Comment by graysonhicks** [comment]
PR to address this in `gatsby-plugin-remote-images` is here if anyone wants to take a look.

https://github.com/graysonhicks/gatsby-plugin-remote-images/pull/30

**Comment by graysonhicks** [comment]
👋 [gatsby-plugin-remote-images](https://github.com/graysonhicks/gatsby-plugin-remote-images) fixed and released in v2.0.0.

**Comment by geekiam** [comment]
Hello 👋🏻
I've faced issue that was mentioned here - https://github.com/gatsbyjs/gatsby/issues/19748

Is there any progress? Do you need any help?

**Comment by axe312ger** [comment]
@vladar i think we can ✅  the Contentful issue?

**Comment by vladar** [comment]
Yup! Thanks for all the work you've put into the plugin to make it happen 👍
