### ISSUE TITLE
Recipes user stories

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#23320]
## Problem
I need to verify that my understanding of current recipes functionality is correct and that my perception of the right next steps also get feedback!

## Solution
Please read these user stories and comment about which ones are already true, which ones are not a good idea, and which ones are missing. After we get agreement, I can turn each of the items below into an issue

With recipes, right now, users can:

- [x] run an available recipe by selecting one from the list OR by running `gatsby recipes [name-of-recipe]`
- [x] run `gatsby recipes` and see a list of available recipes 
- [x] see the proposed change for each step of the recipe, including packages that will be installed and/or a diff of a code change
- [x] know the status of each step of the recipe (did the step succeed? If not, what was the error?)
- [x] create their own recipe

Next, the user will be able to:
- [ ] see what plugin options have been hard-coded for them by the recipe
- [ ] try and discard a recipe quickly (potentially run a recipe that creates a test branch and immediately runs the recipe for you)
- [ ] string multiple recipes together (aka “compose”) into a saved composition
- [ ] run a recipe setting up MDX
- [ ] see all steps of the recipe without previous steps being deleted
- [ ] uninstall a recipe

Later, the user will be able to:
- [ ] see all recipes they’ve run in a project
- [ ] input information into the recipe, like selecting plugin options and entering values for plugin options
- [ ] search for recipes
- [ ] etc (much more to do, not worth diving into yet imo)

**Comment by shrthnd** [comment]
The current user-stories appear spot-on from my perspective, and is not an insignificant amount of work. Thanks, folks!

[This note](https://github.com/gatsbyjs/gatsby/pull/22709#issuecomment-607923725) mentions the possibility of "different designs that e.g. take you back to a main recipes screen"—this would be useful. Could this behavior could be the default (without a --quiet flag or, if you're not running multiple/sequential recipes?)

All good stuff for the future:
- [x] see what plugin options have been hard-coded for them by the recipe
- [x] try and discard a recipe quickly (potentially run a recipe that creates a test branch* and immediately runs the recipe for you)
- [x] string multiple recipes together (aka “compose”) into a saved composition
- [x] run a recipe setting up MDX
- [x] see all steps of the recipe without previous steps being deleted**
- [x] uninstall a recipe
- [x] see all recipes they’ve run in a project**
- [x] input information into the recipe, like selecting plugin options and entering values for plugin options (could be very "block like")
- [x] search for recipes... published in a community "[recipe book](https://github.com/gatsbyjs/gatsby/issues/22991#issuecomment-615379459)"?

Misc. thoughts on the CLI: 
- [ ] *Require git commit/stash before proceeding (unset w/ flag)
- [ ] List local recipes in CLI
- [ ] **Add installed recipes to ./recipes (also, allow for shadowing between dependent recipes)
- [ ] "the ability to locally reference files within a repo" ([source](https://github.com/gatsbyjs/gatsby/issues/22991#issuecomment-614963406))
- [ ] "the ability for recipes to import other recipes" ([source](https://github.com/gatsbyjs/gatsby/issues/22991#issuecomment-615030049))
- [ ] Replace the spinning loading indicator with a measurable indication of progress? 
- [ ] Clarify "recipes" in docs vs `gatsby recipes` (or, convert docs to actionable gatsby recipes?) ([source](https://github.com/gatsbyjs/gatsby/issues/23321))

Aside: any chance you've thought about adding a similar prompt/interface when running `gatsby new`? Even without an interface `gatsby new hello-world` (for official starters) would be handy.

Hope this helps validate some assumptions, @shannonbux. Good luck!

**Comment by shannonbux** [comment]
Thank you @shrthnd for the thoughtful response! 

> Replace the spinning loading indicator with a measurable indication of progress?
Agreed! Here's an initial way of adding more info abt progress: https://github.com/gatsbyjs/gatsby/pull/23362

> Clarify "recipes" in docs vs gatsby recipes (or, convert docs to actionable gatsby recipes?) (source)
Also very much agree abt this lol. *which* recipes do people mean? @laurieontech and @AishaBlake and I talked about nicknaming the new ones "roborecipes". I think we'll need to make sure googling and searching gatsbyjs.org docs makes both kinds of recipes clear.

Curious what use case these behaviors would support (aka why would these be valuable?. I'm not a professional dev so learning here!
> *Require git commit/stash before proceeding (unset w/ flag)
> **Add installed recipes to ./recipes (also, allow for shadowing between dependent recipes)

**Comment by shrthnd** [comment]
Happy to help, @shannonbux. 

The progress indicator noted in [#23362](https://github.com/gatsbyjs/gatsby/pull/23362) looks like a meaningful improvement. I see it's merged into `master` but doesn't show up for me after installing the latest gatsby-cli and gatsby packages (this is probably a user error on my part but I'll have to revisit later.)

> I think we'll need to make sure googling and searching gatsbyjs.org docs makes both kinds of recipes clear.

Conceptually, the idea/metaphor of "gatsby recipes" as opinionated workflows/best-practices, and "gatsby [cli] recipes" as composable scripts which allow people to automate their workflows, feels complementary/natural, and reinforces some of the nicest aspects of working with this framework.

Adding a visually distinct message/callout to the existing recipes docs might help (at least until this is sorted out):

![image](https://user-images.githubusercontent.com/25191/80210925-9f5dc280-8602-11ea-8ff4-897952caa75d.png)


> *Require git commit/stash before proceeding (unset w/ flag)

What got me thinking about this is, after creating a new project, Gatsby automatically initializes an empty git repository and "commits" the project in an untouched state. This allows me to freely experiment and roll back any changes I've made to the project without worrying about losing my work.

At least in my head, Gatsby `recipes` are composable layers which apply a distinct set of changes to a project. In some cases, these changes could be significant and might overwrite files previously created by another recipe or purpose. (Does the order of recipes matter? Probably very much so...) 

Changes should be obvious in the recipes diff, but what if a recipe fails or produces an unintended result? On the other hand, maybe it should be up to the dev to code responsibly? I'm not too opinionated about this one, just exploring possibilities.

> **Add installed recipes to ./recipes (also, allow for shadowing between dependent recipes)

Adding installed recipes to a ./recipes folder might be useful for reviewing which recipes have already been installed in a project. What if I like a recipe but it needs a little more salt? In this case I would make necessary project-specific changes to the local copy of a recipe, and then re-apply the modified recipe. (If the project was committed prior to installing a recipe, I could roll back all changes except the local copy of the recipe...)  

Similarly, if a recipe depends on another recipe, placing an analogously named file in my local ./recipes folder would be a convenient way to override the behavior of nested recipes.

...just thoughts. Keep what works and throw out the rest.

**Comment by shrthnd** [comment]
Hey @shannonbux, I reinstalled the latest release last night and the progress indicator worked as  expected. This feels much better--thank you for prioritizing.

**Comment by shannonbux** [comment]
Just used this idea in a PR, thanks @shrthnd! https://github.com/gatsbyjs/gatsby/pull/23767#issuecomment-626002495. Not sure how to make it visually stand out more, hopefully it at least solves the discoverability problem in the short term :)

Also, apologies for late reply; was on the road/traveling. 

Finally, would you be available to look at some prototypes of recipe composition / editing that we're working on? https://calendly.com/shannon-soper/gatsby-admin-and-recipes or email me shannon@gatsbyjs.com if those times don't work!

**Comment by shrthnd** [comment]
Cool beans, @shannonbux. There's definitely no need to apologize. 

I would be _delighted_ to see what you're baking up (from the perspective of a wandering dev camped at the bottom of this mountain.) Appreciate the opportunity to contribute!

**Comment by shrthnd** [comment]
> Not sure how to make it visually stand out more...

How about a variation of the existing Pullquote component, which looks like this:

![image](https://user-images.githubusercontent.com/25191/81883068-4aa6cb00-9562-11ea-8b2f-6e06987fee61.png)
