### ISSUE TITLE
Umbrella Issue: Gatsby Blog Theme 1.6

### ISSUE THREAD

**Issue by laurieontech** [gatsbyjs/gatsby#23640]
This issue tracks the work being done for the 1.6 release. This is separate from the 2.0 release.

- [x] Social card images
- [x] Featured images
- [x] Toggle off `gatsby-plugin-theme-ui`
- [x] Support external URLs for images
- [x] Variable excerpt length
- [x] Update READMEs

**Comment by ehowey** [comment]
Hey Laurie,

Looking forward to follow this one! Cool to see where themes are headed.

Two thoughts from playing around with the `gatsby-theme-blog-core` and extending it in some of my own work. I basically just took the core theme and tweaked a bit.

You can see what I did here: https://github.com/ehowey/gatsby-theme-catalyst/blob/master/themes/gatsby-theme-catalyst-blog/gatsby-node.js

- Having a single "featured image" field in frontmatter is limiting. The featured image is often different from what people want shared as the social image. I split this out as two separate image fields, `featuredImage` and `socialImage`. Then depending on how the SEO component is setup the featured image could be passed to it or the social image.  I noticed you put in fields for the alt tags, great idea. I was just passing the blog post title in as the alt.

- Being able to customize the excerpt length is nice-to-have, I did this via a theme option in gatsby-config, I felt 140 characters was too short for some designs

**Comment by laurieontech** [comment]
Thanks for the feedback @ehowey! That's an interesting thought on social vs. featured image. Perhaps it can default to the featured one if you don't explicitly set a social image? Does that seem reasonable?

In terms of customizing excerpt length that's certainly something I hadn't considered. I love it!

**Comment by ehowey** [comment]
Looks awesome Laurie, glad those were helpful suggestions.

The only other fields I have seen some use with are a `subTitle` field and a `postType` field, but that is maybe adding unnecessary layers into the theme depending on what the final vision is.  Both of them are optional fields, postType just defaults to "article", but theoretically it would give you a way to display different postTypes with different formats, e.g. you could have a "featured" post type that looked different or a "photo" post type that looked different. But that would require people to know more about customizing themes than is your intended audience maybe?

**Comment by laurieontech** [comment]
Those are both interesting. I think in terms of 1.6 changes this is likely where we'll stop. However, as we develop 2.0 we can certainly consider whether those are worth including.

**Comment by ehowey** [comment]
Sounds good - let me know if there is a smaller part I can help with!

**Comment by laurieontech** [comment]
This is live in gatsby-theme-blog 1.6 and gatsby-theme-blog-core 1.5
