### ISSUE TITLE
After each step and at end of recipe, user knows which files have been edited by recipe

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#23816]
## Problem

A best practice for good user experience is to give the user feedback about their actions. When they perform an action, the system should communicate:
- what is the status of the action? (success/failure/warning)
- what was the action?

We are doing a good job answering the first question with showing a checkmark when a step is successful. What we need to do is answer the second question. What was the action? 

## Solution
The three ways we can do this in the CLI are:
- [x] After each step and at the end of the recipe, user should know which files have been edited/created/deleted by the recipe #23817 
- [ ] Automatically add comments in files that have been edited by a recipe to show what lines have been edited #23819
- [x] Don't delete the steps of a recipe, so the user can see what the past steps included #23818
