### ISSUE TITLE
Umbrella Issue: Gatsby Theme Blog 2.0

### ISSUE THREAD

**Issue by laurieontech** [gatsbyjs/gatsby#23910]
This issue tracks the ongoing and upcoming work for gatsby-theme-blog and gatsby-theme-blog-core 2.0.

Work being tracked on #23351 

- [x] core as semantic HTML, unstyled blog theme
- [ ] core includes classNames as styling hooks
- [x] remove dark mode toggle (potentially separate theme)
- [x] default prism and preset options
- [x] skip nav and additional accessibility audit
- [x] refresh gatsby-theme-ui-preset
- [ ] docs update

Changes elsewhere to support 2.0:
- gatsby-plugin-theme-ui takes preset options
- theme-ui typography handles fonts
- prism highlighting
- prism preset docs page

Currently being worked on in https://github.com/gatsbyjs/themes
