### ISSUE TITLE
[Umbrella] Rename Zeit to Vercel

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#24019]
*Note: please wait for classification of this issue from @gatsbyjs/learning before submitting PR*

## Description

Zeit is now renamed to Vercel.

Important renamings:

- ZEIT → **Vercel**
- ZEIT Now → **Vercel**
- ZEIT Smart CDN → **Vercel Edge Network**

## References

- [Vercel Banding Timeline](https://www.notion.so/Change-Timeline-fab7622780694753a92c0a396cea7eb6)
- [Vercel Branding FAQ](https://www.notion.so/Frequently-Asked-Questions-c726facaf7cc41c095ba49aeea90219e)

## Steps to reproduce

search repo for zeit: https://github.com/gatsbyjs/gatsby/search?q=zeit&unscoped_q=zeit

## Note

some changes (for example GitHub repo are) available after 20. May 2020 -> see time line

## Changes

All changes described in [Timeline](https://www.notion.so/Change-Timeline-fab7622780694753a92c0a396cea7eb6)

Brand names:
- `Zeit` to `Vercel`
- `Now` to `Vercel`
- `Zeit Now` to `Vercel`
- `Now CLI` to `Vercel CLI`
- `ZEIT` to `Vercel`

Commands:
- `now` to `vercel`

Environment:
- `NOW_*` to `VERCEL_*`

Domains:
- `zeit.co` to `vercel.com`
- `now.sh` to `vercel.app`

GitHub:
- `/zeit` to `/vercel` (after 20. May 2020)

## Places to change

Note: only searched for Zeit but not so much for Now, added some now places

### Unclassified occurrence

- [x] (@muescha in #24021 *merged*) [www/src/data/sidebars/doc-links.yaml](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml)

  ```
  78 - title: Deploying to ZEIT Now
  79   link: /docs/deploying-to-zeit-now/
  80   breadcrumbTitle: ZEIT Now
  ```

- [x] (@muescha in #24016 *merged*) [docs/docs/deploying-to-now.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/deploying-to-now.md) 
  -> remove duplicate file of [docs/docs/deploying-to-vercel.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/deploying-to-vercel.md) 

- [x] (@iamdarshshah in #24022 *merged*) [docs/starters.yml](https://github.com/gatsbyjs/gatsby/blob/master/docs/starters.yml)
  ```
  5472 - Continuous deployment via Netlify or Zeit.
  5893 zeit
  5904 - Custom server to test Production Builds on your local network via zeit/serve
  ```

- [x] (@darkmtr in #24120 *merged*) [/docs/recipes/deploying-your-site.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes/deploying-your-site.md)
	- in section: ### Directions
	- what: references to now

- [x] (@iamdarshshah in #24026 *merged*) [docs/blog/100days/free-hosting/index.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/100days/free-hosting/index.md)
  ```				
  34 and [ZEIT Now](/docs/deploying-to-zeit-now/).
  ```
- [x] (@iamdarshshah in #24785 *merged*) [docs/blog/2017-10-03-smartive-goes-gatsby/index.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/2017-10-03-smartive-goes-gatsby/index.md)
  ```
  48 [Next.js](https://github.com/zeit/next.js/), as seemingly everyone going for a
  ```
- [x] (@iamdarshshah in #24785 *merged*) [docs/blog/2017-10-29-my-search-for-the-perfect-universal-javaScript-framework/index.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/2017-10-29-my-search-for-the-perfect-universal-javaScript-framework/index.md)
  ```
  58 I’ll also mention [next.js](https://github.com/zeit/next.js) which is quite
  ```
- [x] (@iamdarshshah in #24026 *merged*) [docs/blog/2019-01-01-publish-multiple-gatsby-sites/index.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/2019-01-01-publish-multiple-gatsby-sites/index.md)
  ```
  464 Now is a tool created by ZEIT that makes
  466 If you haven’t used Now before, then go-ahead and [get started](https://zeit.co/now#features)
  ```

- [x] (@muescha in #24877) [docs/blog/2019-01-01-publish-multiple-gatsby-sites/index.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/2019-01-01-publish-multiple-gatsby-sites/index.md)
	- in section: ### Vercel
	- what: references to now

- [x] (@iamdarshshah in #24026  *merged*) [docs/blog/2019-01-25-blazing-fast-development-with-gatsby-and-sanity-io/index.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/2019-01-25-blazing-fast-development-with-gatsby-and-sanity-io/index.md)
  ```
  130 either [Now](https://zeit.co)
  ```
- [x] (@iamdarshshah in #24026  *merged*) [docs/blog/2019-04-06-security-for-modern-web-frameworks/index.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/2019-04-06-security-for-modern-web-frameworks/index.md)
  ```
  113 They are not the only ones: Azure, Google, Amazon, Zeit.co,
  ```
- [x] (@iamdarshshah in #24026 *merged*) [docs/blog/2019-11-14-announcing-gatsby-cloud/index.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/2019-11-14-announcing-gatsby-cloud/index.md)
  ```
  101 like Heroku, Netlify, Zeit,
  ```
- [x] (@iamdarshshah in #24026 *merged*) [docs/docs/building-a-contact-form.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/building-a-contact-form.md)
  ```
  159 This initial implementation listens for POST requests to `/contact`, and sends you an email with the submitted form data. You can deploy this server with services such as [Now](https://zeit.co/now).
  ```
- [x] (@iamdarshshah in #24024 *merged*) [docs/docs/caching.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/caching.md)
  ```
  50 When deploying with Now, follow the instructions in the [Now documentation](https://zeit.co/guides/deploying-gatsby-with-now#bonus:-cache-your-gatsby-assets).
  ```
- [x] (@iamdarshshah in #24024 *merged*) [docs/docs/deploying-to-vercel.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/deploying-to-vercel.md)
  ```
  9 ## Step 1: Installing Now CLI
  14 npm install -g now
  31 - [Example Project](https://github.com/zeit/now/tree/master/examples/gatsby)
  ```

- [x] [docs/docs/deploying-to-vercel.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/deploying-to-vercel.md)
	- [x] (@stackrole-dev in #24119 *merged*) what: still refer to now cli and to zeit github 
	- [x] `https://gatsby-functions.now-examples.now.sh`
	- [x]  (@iamdarshshah in #24786 *merged*) `[Example Project](https://github.com/zeit/now/tree/master/examples/gatsby)`
	- note: github change is available after 20.may

- [x] (@iamdarshshah in #24026 *merged*) [docs/docs/preparing-for-deployment.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/preparing-for-deployment.md)
  ```
  49 - [ZEIT Now](/docs/deploying-to-zeit-now)
  ```
- [x] (@iamdarshshah in #24026 *merged*) [docs/docs/recipes.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes.md)
  ```
  132 - [Deploying to ZEIT Now](/docs/recipes/deploying-your-site#deploying-to-zeit-now)
  ```
- [x] (@iamdarshshah in #24026 *merged*) [docs/docs/glossary/continuous-deployment.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/glossary/continuous-deployment.md)
  ```
  10 and [Zeit](https://zeit.co/)
  ```
- [x] (@iamdarshshah in #24026 *merged*) [docs/docs/recipes/deploying-your-site.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes/deploying-your-site.md)
  ```
  85 ## Deploying to ZEIT Now
  87 Use [Now CLI](https://zeit.co/download) to deploy your Gatsby application without leaving the command-line interface.
  91 - A [ZEIT Now](https://zeit.co/signup) account
  93 - [Now CLI](https://zeit.co/download) package installed
  106 - [Deploying to ZEIT Now](/docs/deploying-to-zeit-now/)
  ```
- [x] (@iamdarshshah in #24786 *merged*) [examples/using-styled-jsx/README.md](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-styled-jsx/README.md)
  ```
  5 Demonstrates using [styled-jsx](https://github.com/zeit/styled-jsx) with the
  ```
- [x] (@darkmtr in #24120 *merged*) [packages/gatsby-core-utils/README.md](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-core-utils/README.md)
  ```
  69 A utility that enhances `isCI` from 'ci-info` with support for ZEIT's Now and Heroku detection
  ```
- [x] (@iamdarshshah in #24786 *merged*) [packages/gatsby-plugin-styled-jsx/README.md](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-styled-jsx/README.md)
  ```
  3 Provides drop-in support for [styled-jsx](https://github.com/zeit/styled-jsx).
  17 You can add styled-jsx [plugins](https://github.com/zeit/styled-jsx#css-preprocessing-via-plugins) with the `jsxPlugins` option
  30 [Configuration options for `styled-jsx`](https://github.com/zeit/styled-jsx#configuration-options) can also be specified:
  ```
- [x] (@iamdarshshah in #24044 *merged*)[starters/README-template.md](https://github.com/gatsbyjs/gatsby/blob/master/starters/README-template.md)
  ```
  96 [![Deploy with ZEIT Now](https://zeit.co/button)](https://zeit.co/import/project?template=https://github.com/gatsbyjs/gatsby-starter-<%= name %>)
  ```

### Usage in comments

- [ ] [packages/gatsby-core-utils/README.md](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-core-utils/README.md)
  ```
  90 // {CI_NAME: "ZEIT Now"}
  ```
- [ ] [packages/gatsby-core-utils/src/ci.ts](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-core-utils/src/ci.ts)
  ```
  37 * Gets the name of the CI environment (e.g. "ZEIT Now", "Heroku", etc.)
  ```

### Usage in string constants

- [x] [packages/gatsby-core-utils/src/ci.ts](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-core-utils/src/ci.ts)
  ```
  5 getEnvDetect({ key: `NOW_BUILDER_ANNOTATE`, name: `ZEIT Now` }),
  6 getEnvDetect({ key: `NOW_REGION`, name: `ZEIT Now v1` }),
  ```
  *Note: i don't know how to solve this? maybe both (new and old) should be valid? `NOW_REGION` and `VERCEL_REGION`?*

- [x] [packages/gatsby-core-utils/src/ci.ts](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-core-utils/src/ci.ts)
  ```
  getEnvDetect({ key: `VERCEL_URL`, name: `Vercel Now` }),
  getEnvDetect({ key: `NOW_BUILDER`, name: `Vercel Now` }),
  ```
  @jamoo added `getEnvDetect` in #25883 `Detect vercel again after rebranding in gatsby-telemetry`

- [x] [packages/gatsby-core-utils/src/ci.ts](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-core-utils/src/ci.ts)

  ```
  getEnvDetect({ key: `VERCEL_BUILDER`, name: `Vercel Now` }),
  ```
  @jamoo added `getEnvDetect` in #25926

- [x] [`packages/gatsby-core-utils/src/__tests__/ci.ts`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-core-utils/src/__tests__/ci.ts)
  ```
  37 expect(getCIName()).toEqual(`ZEIT Now`)
  45 expect(getCIName()).toEqual(`ZEIT Now v1`)
  ```

**Comment by iamdarshshah** [comment]
@muescha Nice catch. Digging into it. Thanks

**Comment by muescha** [comment]
oh - that was a draft, i updated it now...

**Comment by muescha** [comment]
please lets wait before some PR for a classification from @gatsbyjs/learning

**Comment by iamdarshshah** [comment]
Sure, Thanks for the quick update.

**Comment by muescha** [comment]
not stale

**Comment by muescha** [comment]
there are left only few places:

- https://gatsby-functions.now-examples.now.sh
- and in the `gatsby-core-utils` package

**Comment by LekoArts** [comment]
Only left is `gatsby-core-utils` now

**Comment by muescha** [comment]
🌟 🚢
