### ISSUE TITLE
Enable paginated synced fetch for gatsby-source-contentful

### ISSUE THREAD

**Issue by wardpeet** [gatsbyjs/gatsby#24118]
## Summary

Currently, we have to download all information from contentful before we start creating nodes. For large sites, this can take up to 10 - 20 minutes on huge sites. Waiting for http requests means our cpu is idle and is being wasted.

If we use the paged sync api we could start downloading and when the first page is downloaded start processing nodes. This would reduce idle time.

Contentful source plugin adds foreign references to each node, so there is a bi-directional link. These links cannot be calculated during this paged fetch. We have to wait until all processing is done. We'll have to introduce a breaking change here and use a custom resolver, so we don't break behavior.

### Todo

- [ ] setup paged fetch without doing paged processing
- [ ] add extra option to enable paged fetching
- [ ] setup paged processing

**Comment by axe312ger** [comment]
closing this as Contentful sync api usage will be improved in #15084 

see: https://github.com/gatsbyjs/gatsby/pull/24604#issuecomment-641933538
