### ISSUE TITLE
☂️ Umbrella issue: Plugin Options Validation

### ISSUE THREAD

**Issue by mxstbr** [gatsbyjs/gatsby#28177]
As of `gatsby@2.25.0`, plugins can define a schema to enforce a type for each of their options. Gatsby will validate that the options users pass match the schema to help them correctly set up their site.

To learn more, **check out [the "How to validate plugin options" documentation](https://www.gatsbyjs.com/docs/configuring-usage-with-plugin-options/#how-to-validate-plugin-options)**.

## How you can help

We need you to please **add `pluginOptionsSchema`s to your own Gatsby plugins**! Once your plugin has a schema, Gatsby can guarantee users it is configured correctly.

If you're looking to contribute to Gatsby, we could also use your help converting the most popular plugins in our monorepo to have `pluginOptionsSchema`s.

If you would like to help us:

1. Select one of the unclaimed plugins below (check the comments first to see if anyone else has claimed it!)
2. Comment in this issue that you're claiming the plugin
3. Look at the documentation for the plugin to figure out which options exist
4. Write a `pluginOptionsSchema` in the plugins' gatsby-node.js file (if it doesn't have one, create it) following the [best practices](https://www.gatsbyjs.com/docs/configuring-usage-with-plugin-options/#best-practices-for-option-schemas)

**Core plugins**

- [ ] gatsby-plugin-canonical-urls
- [ ] gatsby-plugin-catch-links
- [ ] gatsby-plugin-create-client-paths
- [x] gatsby-plugin-cxs
- [x] gatsby-plugin-emotion
- [x] gatsby-plugin-feed
- [x] gatsby-plugin-glamor
- [x] gatsby-plugin-google-analytics
- [ ] gatsby-plugin-google-gtag
- [x] gatsby-plugin-google-tagmanager
- [ ] gatsby-plugin-image
- [ ] gatsby-plugin-layout
- [ ] gatsby-plugin-less
- [ ] gatsby-plugin-lodash
- [x] gatsby-plugin-manifest
- [x] gatsby-plugin-mdx
- [x] gatsby-plugin-netlify
- [ ] gatsby-plugin-netlify-cms
- [ ] gatsby-plugin-nprogress
- [x] gatsby-plugin-offline
- [ ] gatsby-plugin-page-creator
- [ ] gatsby-plugin-postcss
- [ ] gatsby-plugin-preact
- [x] gatsby-plugin-react-helmet
- [ ] gatsby-plugin-remove-trailing-slashes
- [x] gatsby-plugin-sass
- [x] gatsby-plugin-sharp
- [x] gatsby-plugin-sitemap
- [x] gatsby-plugin-styled-components
- [ ] gatsby-plugin-styled-jsx
- [x] gatsby-plugin-twitter
- [x] gatsby-plugin-typescript
- [ ] gatsby-plugin-typography
- [x] gatsby-remark-autolink-headers
- [ ] gatsby-remark-copy-linked-files
- [x] gatsby-remark-images
- [ ] gatsby-remark-images-contentful
- [ ] gatsby-remark-prismjs
- [ ] gatsby-remark-responsive-iframe
- [ ] gatsby-remark-smartypants
- [x] gatsby-source-contentful
- [ ] gatsby-source-drupal
- [x] gatsby-source-filesystem
- [ ] gatsby-source-graphql
- [ ] gatsby-source-shopify
- [ ] gatsby-source-wordpress
- [ ] gatsby-transformer-json
- [x] gatsby-transformer-remark
- [ ] gatsby-transformer-sharp
- [ ] gatsby-transformer-yaml
