### ISSUE TITLE
IA restructure for guides

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#4341]
## Description

Usability testing to do after tasks below are done:
- [x] Develop personas of the types of people who visit gatsbyjs.org and what they're looking for (for example, non-programmers vs. engineering managers vs. experienced programmers, etc.)
- [x] a card sort to see how different personas naturally categorize current docs (we could throw in some new titles for docs we know we're going to create soon)
- [x] then do usability testing to see if the architecture has improved
- [x] make improvements based off of usability testing
- [ ] Make templates for each kind of doc
- [ ] get RFC merged

## Help needed

For usability testing, I need two things:
1. a set of 5-10 discrete tasks a person might try to accomplish by visiting the docs. I will give these tasks to people and record how they accomplish (or don't accomplish) the task.
2. Volunteers who are willing to let me Skype with them / meet in person to watch them try to accomplish said tasks above. Volunteers would need to be unaware of the tasks ahead of time.

Re no. 3 above, here's one possible way to classify the kinds of templates we could produce for docs. On the site itself, we would want to categorize possibly by these categories with more specific categories nested inside. I'll have to find out more by usability testing.
<img width="811" alt="copy of screen shot 2017-10-12 at 1 08 39 pm" src="https://user-images.githubusercontent.com/32467162/37122478-8d5149b6-2215-11e8-8559-dfa28cecb3b1.png">

**Comment by LeKoArts** [comment]
> a set of 5-10 discrete tasks a person might try to accomplish by visiting the docs. I will give these tasks to people and record how they accomplish (or don't accomplish) the task.

Here are some ideas:

- Installing the Gatsby CLI and starting a new project
- Installing a plugin (Also: Are the instructions on these plugins clear enough and consistent)
- Creating an own plugin
- Contribute to the project (Adding README etc.)
- See what has changed/migrating (We still lack a proper changelog)

**Comment by shannonbux** [comment]
@LeKoArts thanks for these ideas! Will report back after I do some testing.

**Comment by shannonbux** [comment]
Updating this issue with a task list:
The sidebar is getting too long. We need to restructure the guides by 
- [ ] adding a second level of navigation with clear content categories and types
- [ ] organize existing documents into new categories
- [ ] publicize a way to place future docs into the right categories
![mvimg_20180314_180540](https://user-images.githubusercontent.com/32467162/37689324-f9a0ab62-2c69-11e8-90b2-f963d56d470e.jpg)
