### ISSUE TITLE
[v2] Issue for tracking upstream work on mini-css-extract-plugin

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#4677]
- [ ] HMR w/ mini-css-extract-plugin webpack-contrib/mini-css-extract-plugin#34
- [x] content hash support webpack-contrib/mini-css-extract-plugin#1
- [x] Don't refetched CSS chunks that are inlined https://github.com/webpack-contrib/mini-css-extract-plugin/issues/53
- [ ] ~Use `[contenthash]` instead of `[chunkhash]`~

@sokra I think you mentioned also that you still need to add support for extracting out common css into shared chunks? Is there an issue for this?

**Comment by m-allanson** [comment]
Split out remaining item into a separate issue.
