### ISSUE TITLE
[v2] Beta 1 Umbrella

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#5132]
- [ ] upgrade guide
- [ ] gatsbyjs.org running on v2
- [ ] add link to v1 docs
- [ ] tests passing
- [ ] switch `v2` to default branch on GitHub
- [ ] migrate PRs to point to `v2` branch (where appropriate - some can be merged to `master` and ported to `v2`)

**Comment by m-allanson** [comment]
I've replaced this with a column in the [v2 project](https://github.com/gatsbyjs/gatsby/projects/2)
