### ISSUE TITLE
Release beta version of v2

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#5762]
- [x] Create next.gatsbyjs.org and point it to v2
- [x] Do a new v2 alpha release
- [x] Do a new v1 release
- [x] Merge master into v2
- [x] Test v2 branch
- [x] Branch v1 from master
- [x] Add note about v2 beta to top of readme
- [x] Add link to migration guide to top of readme
- [x] Update `v2---` netlify links to `next.gatsbyjs.org`
- [x] Force pull `master` into `v1`
- [x] Change netlify to build gatsbyjs.org from `v1` branch
- [x] add a robots.txt to the `v2` branch (#5952)
- [x] Add a banner pointing from `next.gatsbyjs.org` to `gatsbyjs.org` (#5915)
- [x] Add docs on which branches to use for PRs while v2 is in beta (#5933)
- [x] Resolve #5899
- [x] Do a fresh `master -> v2` merge
- [x] Publish final alpha release
- [x] Merge `v2` into `master`
- [x] Update `next.gatsbyjs.org` to point to `master`
- [x] Switch to lerna v3
- [x] Publish beta 1 to npm
- [x] Merge v2 beta blog post to `v1` branch

**Comment by m-allanson** [comment]
Set up `new.gatsbyjs.org` as a generic "upcoming version of Gatsby" preview site? See new.babeljs.io.

**Comment by nihgwu** [comment]
what about `next.gatsbyjs.org` as we are using `next` tag for the coming `v2`

**Comment by KyleAMathews** [comment]
👍 to `next` since that's reusable. Also Babel use(d|s) new because it's a site rebuild and not specifically for the next version of Babel.

**Comment by m-allanson** [comment]
@KyleAMathews can you setup the DNS for `next.gatsbyjs.org` and create the site in Netlify? I'm 98% certain I could do the netlify side of things, but don't want to click a wrong button and break gatsbyjs.org.

**Comment by KyleAMathews** [comment]
Beta is out!!! Thanks @m-allanson and @pieh and many others for all your contributions! Let's push on to a v2.
