### ISSUE TITLE
[v2] Upgrade three official starters on their v2 branch

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#5973]
I probably won't get to this today so if someone else wants to work on it, that'd be great!

- [x] upgrade three official starters on their v2 branch 
- [x] link to them from the announcement blog post (#6073)
- [x] link to them from the upgrade guide on next.gatsbyjs.org
- [x] link to them from the quickstart on next.gatsbyjs.org (#6070)
- [x] link to them from the readme (#6070)
- [x] link to them in the “Life After Layouts” post (#5816)

Edit: created checklist from issue title, shortened title

**Comment by mottox2** [comment]
I updated gatsby-starter-default to v2.
Please create v2 branch to gatsby-starter-default repository to make pull request.

https://github.com/gatsbyjs/gatsby-starter-default/compare/master...mottox2:v2?expand=1

**Comment by jlengstorf** [comment]
@mottox2 I just created a v2 branch: https://github.com/gatsbyjs/gatsby-starter-default/tree/v2

Thank you!

**Comment by m-allanson** [comment]
Note - `gatsby new` can parse branch names, so you can install v2 versions of starters. Check out the v2 tutorial for an example of this.

**Comment by jlengstorf** [comment]
A link to that tutorial: https://next.gatsbyjs.org/tutorial/part-one/#install-the-hello-world-starter

**Comment by KyleAMathews** [comment]
This work is done. Thanks for everyone's help!
