### ISSUE TITLE
[Sub-Epic] v2 Pre-Release ToDos

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/gatsby#6869]
This will hold all issues that need to be completed before Gatsby v2 Release, but do *not* fall under UX & Docs, Bugs, or Breaking Changes.

Pre-Release ToDo List (referenced from #5953, which is also included in this sub-epic)
- [x] change wordpress/drupal source plugins dependency from `next` back to version range
- [x] remove `--allow-next` flag from `check-versions` script in `package.json`
- [x] change all examples' package.json to use `^2.0.0` (or whatever new latest is) for each plugin
- [ ] Remove robots.txt from www/static in prep for moving building gatsbyjs.org to master again
- [x] Merge `v2` branch into to `master` in official starters
- Change installation instruction in docs to use `master` branches of starters
   - [x] Get Started: (revert #6685)
   - [x] Main Tutorials
   - [x] Source Plugin Tutorial (revert #6857)
