### ISSUE TITLE
[EPIC] Docs IA redesign MVP

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6899]
## MVP
- [x] add a second (possibly third) level to docs navigation in the sidebar in accordion style menu, e.g. how do we make the sidebar not too long or overwhelming?
Expand top (and potentially second-level) navigation items that do not belong to the current section on user interaction (see e.g. https://reactjs.org/, https://stripe.com/docs/stripe-js for second-level)
- [x] Selected state for sidebar items
    - Maybe the current “bullet point” doesn’t work very well for indented navigation items
    - The current purple doesn’t stand out enough
    - The use of the “bold” Futura may cause the navigation item text to take one more line than the default “normal” Futura state, causing the navigation items below to change their position
    - Digital Ocean does cool selected state and hover state stuff: https://developers.digitalocean.com/documentation/v2/#authentication
- [x] create new categories of docs. When clicked, the only thing that happens is that sub-items become visible and the active page remains the same as it was before clicking the category name until a sub-item is clicked. So essentially, clicking on a sub-item is the only way to see a new active page.
- [x] create stub articles for the ones we don’t have yet
- [x] mobile menu that you can access w/o scrolling to bottom of screen
    - Currently https://www.gatsbyjs.org/docs/ is the only way on Mobile to access the Desktop sidebar content
    - https://reactjs.org/ is an excellent example of a Mobile navigation for our sidebar content, but the button position conflicts with our current mobile navigation
    - Noteworthy: the equally excellent https://stripe.com/docs/quickstart and https://stripe.com/docs/api completely ignore smaller screens

## RFC
https://github.com/gatsbyjs/rfcs/pull/5

**Comment by calcsam** [comment]
@shannonbux should we close this?
