### ISSUE TITLE
[EPIC] Docs IA redesign phase 3

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#6901]
Phase 3:
- [ ] API on top level nav
- [ ] versions of the docs
- [ ] Way to test APIs. Ask devs for their favorite ones. 
- [ ] automatically pull in doc prereqs at top of each page (see https://www.cockroachlabs.com/docs/stable/transactions.html as a great example of how to design this. Not sure how to code it)
- [ ] doc accessibility/design options (changing font type and size or screen and font colors, what about language?), toggle sidebar to disappear, reappear
- [ ] searchable API reference
- [ ] track one ideal "paths" through the docs to see if idea is worth expanding
- [ ] a breadcrumb trail (like Amazon does) 
- [ ] suggesting "next steps" at the bottom of docs
- [ ] vet feasibility/desirability of new project that focuses on enhancing our search results (perhaps pulling in Google search, showing previews, etc)

**Comment by jsjoeio** [comment]
Some things I wanted to share as well!
>https://nextjs.org/learn/ - Next.js has this cool tutorial with questions at the end of each section. Could be cool for future Gatsby tutorials!
>https://www.twilio.com/quest/welcome - TwilioQuest - "TwilioQuest is an interactive, self-paced game where you learn how to Twilio." used this to learn how to use Twilio! Also another fun thing to consider for future Gatsby tutorials.

**Comment by shannonbux** [comment]
Great search page design: algolia.com/doc (thanks @cdock1029 for this idea)

**Comment by fk** [comment]
💯agreed on the algolia reference! I'd like to think that we're a tiny step closer to something comparable with the "landing page" approach shown in https://github.com/gatsbyjs/gatsby/issues/7544#issuecomment-416293476?
Even if I'm not very far into the design of that page, I'd love to hear your thoughts over there @shannonbux and everyone!
