### ISSUE TITLE
[EPIC] Docs IA redesign phase 2

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7128]
We already finished the MVP. Now it's time for phase 2 as outlined in the RFC

[RFC](https://github.com/gatsbyjs/rfcs/pull/5).

# How to Use This Epic
This Epic was created as a living document to house issues, feature requests, and bugs associated with Docs redesign phase 2.

It will also define who is in charge of what.

**This is a living list of information, and can be updated as needed**

Phase 2 features:
- [ ] write instructions for contributors to fill out stub articles
- [ ] choose gold standard examples of docs for contributors to imitate (different gold standard for each type of doc)
- [ ] publish templates for each category of docs to facilitate contributions and contract work
- [ ] rename titles of docs to make them more concise and add redirects
- [ ] Every month (or some amount of time), do a docs sprint for a new section of the docs
- [ ] Add issue submission form at bottom of each doc (alternative icons? Smileys including neutral face?)
- [ ] Popup/slideout form that asks people: What are you looking for on gatsbyjs.org today? with a rating/form to ask if they found what they're looking for. Other questions: "How can we improve?"
- [ ] Way to copy and paste code easily Ref. gatsbyjs/gatsby#5030

Known Issues and Bugs:

**How to read this dashboard**
1. Scroll down and find the PRs Opened / PRs Closed chart
2. What we'd hope to see is a steady increase in PRs opened, correlated with an increase in PRs being closed as well. We would hope that this increase coincides with the launch of phase 2 of the redesign. 

### See how people use the gatsbyjs.org docs
You can look through selected videos and dashboards about how people use the Docs section of gatsbyjs.org
* [Airtable interview notes & Zoom recordings]()
* [Fullstory](link will go here)
* [Algolia search results](link will go here)

# Resources
_Below is the running list of resources for the project._

### Flow Chart | Process

Soon we'll come up with flow charts to describe the ideal user pathway(s) through the docs.

### RFC

[RFC](https://github.com/gatsbyjs/rfcs/pull/5)
