### ISSUE TITLE
[EPIC] Plan Portland Gatsby Meetup

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#7227]
## Tentative details (subject to change)

- 	August 23, 2018
- 	6:30pm
- 	Alchemy Code Lab
	30 NW 10th Avenue
	Portland, OR 97227

## TODO

- [x] Find a venue (Thanks for hosting, [Alchemy Code Lab](https://www.alchemycodelab.com/)!)
- [x] Find an A/V company to record videos (#7234)
- [x] Decide on what talks will be at the meetup (#7235)
- [x] Get food and drinks figured out (#7236)
- [x] Get the details posted on Meetup.com (#7237)
- [x] Post the meetup to all social channels (#7238)

Am I missing anything else?

I'm really looking forward to this! This event is free and open to anyone who'd like to join, so anyone in the community who's close to the Portland area, we hope to see you there!

**Comment by kylegalbraith** [comment]
@jlengstorf Sounds really cool! I live in Portland as well and would love to attend. I could potentially give a talk on how I used Gatsby to stand up my blog, [here is a post](https://blog.kylegalbraith.com/2018/08/07/how-to-make-an-awesome-blog-using-gatsbyjs-and-aws/). But either way, anything I can do to help please let me know. 

Is there a date picked yet?

**Comment by amberleyromo** [comment]
Two more possible talk topics: Routing (reach/router, and routing accessibility) and data in v2 (more technical detail than what you described for v2, in terms of the implementation difference between v1/v2)

**Comment by jlengstorf** [comment]
Thanks, @kylegalbraith and @amberleyromo! I updated #7235 with details and questions. I broke this up into an epic because there are lots of moving pieces and I don't want to drop any.

**Comment by lindaleebumblebee** [comment]
I've drafted the copy to promote the event here: https://docs.google.com/document/d/1tmLXYZNQqJR-VmwIlrAR9DaIjhknJxL5FRq4g6uLMlE/edit
@jlengstorf will you review and make sure I'm referring to V2 correctly? Thanks!

**Comment by chasemccoy** [comment]
XOXO is happening in Portland September 6-10. It would be awesome to have this during the festival so that out-of-towners can come!

**Comment by jlengstorf** [comment]
Hey, @chasemccoy — unfortunately, we've only got the whole team in town next week. However, I live in Portland — hit me up when you're here!

**Comment by jlengstorf** [comment]
Talks were recorded and are on our YouTube channel: https://youtu.be/7M-7GlQGeGc?t=16m33s

Thanks so much to everyone who helped out, showed up, watched the livestream, and otherwise made this event a great success. You’re all amazing! 💪💜
