### ISSUE TITLE
[EPIC] v2.0 Starter Library

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7558]
### Who will own this?

_What Area of Responsibility does this fall into? Who will own the work, and who needs to be aware of the work?_

**Area of Responsibility:**

_Select the Area of Responsibility *most impacted* by this Epic_

- [ ] Community
- [ ] Learning
- [x] Ecosystem
- [ ] Gatsby Core
- [ ] Enterprise
- [ ] Design
- [ ] Marketing
- [ ] Company/Admin
- [ ] Sales

     |                 |       |
     | --------------- | ----- |
     | AoR owner       | @amberleyromo  |
     | Domain owner   | @name |
     | Project manager | @name |
     | Tech lead       | @name |
     | Contributors    | @name |

### Summary

We want to take the starter showcase to the next level of helpfulness, mostly by increasing the number of sorting and filtering capabilities and creating a creator's showcase functionality so there is visibility into creators of starters.

### How will this impact Gatsby?

**Domains**

_List the impacted domains here_

**Components**

_List the impacted Components here_

### Goals

_What are the top 3 goals you want to accomplish with this epic? All goals should be specific, measurable, actionable, realistic, and timebound._

1.  
2.  
3.

### How will we know this epic is a success?

_What changes must we see, or what must be created for us to know the project was a success. How will we know when the project is done? How will we measure success?_

**User Can Statement**

- User can...

**Metrics to Measure Success**

- We will see an increase /decrease in...

### Additional Description

_In a few sentences, describe the current status of the epic, what we know, and what's already been done._

### What are the risks to the epic?

_In a few sentences, describe what high-level questions we still need to answer about the project. How could this go wrong? What are the trade-offs? Do we need to close a door to go through this one?_

### What questions do we still need to answer, or what resources do we need?

_Is there research to be done? Are there things we don’t know? Are there documents we need access to? Is there contact info we need? Add those questions as bullet points here._

## Phase 2:

It would be nice if users could:
- [x] see which starters are official
- [ ] read about creators of starters (and see all starters they have submitted) (will need to coordinate with Creator's Showcase project)
- [ ] Sort by "last updated" date
- [ ] Sort by popularity
- [x] Filter by category or tag (filtered index page)
- [x] Share sites with a social media / URL copy button in a modal
- [x] learn how to make a starter (tutorial?)

contributors should be able to:
- [ ] easily check whether a starter submission has all required fields (Peril automation?)

## MVP
#905

#Phase 3
#7562 

### How else could we accomplish the same goal?

_Are there other ways to accomplish the goals you listed above? How else could we do the same thing?_
