### ISSUE TITLE
[EPIC] v3.0 Starter Library

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7562]
### Who will own this?

**Area of Responsibility:**

_Select the Area of Responsibility *most impacted* by this Epic_

- [ ] Community
- [ ] Learning
- [x] Ecosystem
- [ ] Gatsby Core
- [ ] Enterprise
- [ ] Design
- [ ] Marketing
- [ ] Company/Admin
- [ ] Sales

     |                 |       |
     | --------------- | ----- |
     | AoR owner       | @amberleyromo  |
     | Domain owner   | @name |
     | Project manager | @name |
     | Tech lead       | @name |
     | Contributors    | @name |

### Summary

This epic organizes some enhancements to the starter showcase that mostly include making sure that there is a way to flow easily between starter showcase <--> site showcase, docs, tutorials, and plugin library.
 
### How will this impact Gatsby?

**Domains**

_List the impacted domains here_

**Components**

_List the impacted Components here_

### Goals

_What are the top 3 goals you want to accomplish with this epic? All goals should be specific, measurable, actionable, realistic, and timebound._

1.  
2.  
3.

### How will we know this epic is a success?

_What changes must we see, or what must be created for us to know the project was a success. How will we know when the project is done? How will we measure success?_

**User Can Statement**

- User can...

**Metrics to Measure Success**

- We will see an increase /decrease in...

### Additional Description

_In a few sentences, describe the current status of the epic, what we know, and what's already been done._

### What are the risks to the epic?

_In a few sentences, describe what high-level questions we still need to answer about the project. How could this go wrong? What are the trade-offs? Do we need to close a door to go through this one?_

## Phase 3

It'd be awesome if users could:
- [ ] See the performance of starters in action (if they have functionality with a visual component, ex. GIFs, performance metrics, data on traffic improvement after the site switched to Gatsby,etc.)
- [x] See a list of all starters that use a particular plugin (this would be a change to the plugin library, probably)
- [ ] Sign up to get notifications or updates when new starters are added (or just sign up for the newsletter?)
- [ ] Click on links to relevant tutorials and docs from each starter

Any more research that needs to be done?

### How will we complete the epic?

_What are the steps involved in taking this from idea through to reality?_

### How else could we accomplish the same goal?

_Are there other ways to accomplish the goals you listed above? How else could we do the same thing?_
