### ISSUE TITLE
[EPIC] v1.0 Starter Library

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7563]
### Who will own this?

**Area of Responsibility:**

_Select the Area of Responsibility *most impacted* by this Epic_

- [x] Ecosystem

|                 |       |
| --------------- | ----- |
| AoR owner       | @amberleyromo   |
| Product owner   | |
| Project manager | |
| Tech lead       | |
| Contributors    | @kkemple, @fk |

### Summary

The /starters/ page is one of the topmost visited pages on www.gatsbyjs.org, and the most important pain point with the page is that it's not filterable or searchable. We want to make it easier for developers to search for starters with the functionality they need so they can save time when starting projects and therefore start and/or finish more projects.

### How will this impact Gatsby?

**Products**

gatsbyjs.org
.org Docs

**Components**

TBD

### Goals

_What are the top 3 goals you want to accomplish with this epic? All goals should be specific, measurable, actionable, realistic, and timebound._

1. Increase official starter usage
2. Increase the number of starters submitted
3. Increase the number of visitors to the starter page

### How will we know this epic is a success?

We will know this epic is a success when the following list of features are shipped and useable.

**User Can Statement**

- User can...
- [x] See what starter looks like (for site showcase we use screenshots; don't know if that'd work for starters)
- [x] Install starter quickly
- [x] See source code of starter
- [x] Share starter
- [x] Filter by category
- [x] Filter by functionality (does this include more than dependencies?)
- [x] Search by keyword
- [ ] Submit their own starter to the showcase through .md file (Shannon to do)
- [x] See a list of the starter's dependencies

**Metrics to Measure Success**

- We will see an increase in usage of official starters
- We will see an increase in the numbers of starters submitted
- We will see an increase in the number of page views of the starter showcase

### Additional description

Research

### See how people use current list of starters (UX research)
You can look through selected videos and dashboards about how people use starters and why we're doing this project:
* [Airtable interview notes & Zoom recordings](https://airtable.com/invite/l?inviteId=invKyr0xFc62ZZtDf&inviteToken=0756d8108516cb2d7e2b516a1b754374701f52bc96de2e4b5146f45959dc0ee6)
* [Fullstory](https://app.fullstory.com/ui/B2TRP/segments/everyone/people:search:(:():():(((EventType:==:%22navigate%22):(PageUrl:%5E$:%22%7C_starters%7C_%22))):():)/0)
* [Algolia search results](https://www.algolia.com/apps/BH4D9OD16A/analytics/popular/gatsbyjs?from=08-22-2018&to=08-29-2018&limit=40&search=starter)

### Summary of research
The starter list is one of the topmost visited pages on www.gatsbyjs.org, and here are all the pain points associated with it:
- People sometimes don't know what starters or Gatsby sites exist
- One interviewee installed several starters that were disappointingly ugly, and he wishes the documentation was more thorough so he knew what he was getting into.
- Some starters are outdated
- People often learn what's possible to build and how to build it by looking at src code for other starters / sites and it takes a long time to find a starter with the functionality they want since the current /starters/ page isn't filterable or searchable.

Potential benefits of bringing a site / starter showcase (also based on interviews):
- *Persuading more people to use Gatsby:* People will have confidence that they can imitate what's already been built if they see it and can look at the src code. It would *also* be cool to have a way of demonstrating that the development experience was awesome. Stories of how quickly they built the sites, or how big the team was, etc. Just to give ppl more motivation and confidence that they can repeat the same process and have a successful result.
- *More highly functional Gatsby sites out in the world:* Many people learn how to build things by looking at src code for other sites. The more sites they can explore the code for, the more likely they are to learn how to build equally functioning sites.
- *Ways of showing not only finished results but also development experience of Gatsby:* People want a showcase of how quickly you can create a site
- *A way of showing how plugins perform*, since many plugins have a visual or performance result that can only be fully experienced by seeing it in practice

### What are the risks to the epic?

- It's possible that people will submit starters that are broken, or they will fill out the `.yml` file incorrectly, which could break the starter showcase
- It's possible that people could confuse the starter and site showcase with each other

### What questions do we still need to answer, or what resources do we need?

- How to measure official starter usage?

### How will we complete the epic?

1. Finish issues below
2. Meet weekly to unblock progress on issues below

### How else could we accomplish the same goal?

_Are there other ways to accomplish the goals you listed above? How else could we do the same thing?_

# Resources
_Below is the running list of resources for the project._

Original project and research done by Shawn Wang:
- demo: https://gatsby-starter-search.netlify.com/
https://5b65f3c6c6aed633f0a87af2--next-gatsbyjs.netlify.com/starter-showcase/
- repo: https://github.com/sw-yx/gatsby-starter-search
- twitter discussion: https://twitter.com/gatsbyjs/status/993954935489282048

## Phase 2
#7558

## Phase 3
#7562

### Gantt Chart | Timeline

TBD

### Flow Chart | Process

Soon we'll come up with flow charts to describe the ideal user pathway(s) through the starter showcase.

**Comment by shannonbux** [comment]
@calcsam

**Comment by amberleyromo** [comment]
Closing out [EPIC] v1.0 Starter Library
