### ISSUE TITLE
[EPIC] v2.0 Site Showcase phase

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7566]
### Who will own this?

_What Area of Responsibility does this fall into? Who will own the work, and who needs to be aware of the work?_

**Area of Responsibility:**

_Select the Area of Responsibility *most impacted* by this Epic_

- [ ] Community
- [ ] Learning
- [x] Ecosystem
- [ ] Gatsby Core
- [ ] Enterprise
- [ ] Design
- [ ] Marketing
- [ ] Company/Admin
- [ ] Sales

     |                 |       |
     | --------------- | ----- |
     | AoR owner       | @amberleyromo |
     | Domain owner   | @name |
     | Project manager | @name |
     | Tech lead       | @name |
     | Contributors    | @name |

### Summary

This epic organizes issues that will help the site showcase become even more helpful by introducing enhanced sorting and filtering functionality and ways to link to the Creator's Showcase.

### How will this impact Gatsby?

**Domains**

_List the impacted domains here_

**Components**

_List the impacted Components here_

### Goals

_What are the top 3 goals you want to accomplish with this epic? All goals should be specific, measurable, actionable, realistic, and timebound._

1.  
2.  
3.

### How will we know this epic is a success?

_What changes must we see, or what must be created for us to know the project was a success. How will we know when the project is done? How will we measure success?_

**User Can Statement**

- User can...

**Metrics to Measure Success**

- We will see an increase /decrease in...

### Additional Description

_In a few sentences, describe the current status of the epic, what we know, and what's already been done._

### What are the risks to the epic?

_In a few sentences, describe what high-level questions we still need to answer about the project. How could this go wrong? What are the trade-offs? Do we need to close a door to go through this one?_

### What questions do we still need to answer, or what resources do we need?

Already did extensive research.

### How will we complete the epic?

*Phase 2*
Users ought to be able to:
- [ ] filter on mobile: @ThatOtherPerson's repo has a PR adding the non-functional UI parts: https://github.com/ThatOtherPerson/gatsby/pull/6
- [ ] filter by whether a site is open source or not
- [ ] Sort by date added (won't matter until ppl start submitting sites)
- [ ] visit a personal page for creators of sites (see all sites they have submitted)

From an OSS perspective, OSS maintainers ought to be able to merge site showcase submission PR's without having to double-check each submission. 
- [ ] Implement Peril automation to validate site showcase submissions

### How else could we accomplish the same goal?

_Are there other ways to accomplish the goals you listed above? How else could we do the same thing?_
