### ISSUE TITLE
[EPIC] Improve OSS process through workflow docs and automation

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7583]
> **NOTE:** This issue is an epic, which bundles up lots of related issues into a single goal. If you have the [free ZenHub extension](https://www.zenhub.com/), you’ll be able to see overall progress and related issues, as well as a "board view" that shows this epic from a bird's-eye view.

## Who will own this?

Role            | Contributor(s)
--------------- | -------------------------------
AoR owner       | @KyleAMathews
Domain owner    | @jlengstorf
Project manager | @marisamorby 
Tech lead       | @jlengstorf
Contributors    | @jlengstorf, @pieh, @m-allanson, @DSchau

## Summary

We want to research the current problems getting in the way of improved OSS maintenance and make sure to solve those problems to improve the maintenance process.

<details>
	<summary><strong>Expand this section for additional details and research</strong></summary>

#### What we know so far:

- Core maintainers' most frequent blocker: not enough time to maintain OSS well
- What happens if OSS doesn't get maintained well? Contributions can get lost, duplicated, forgotten, stalled, or prioritized incorrectly (all of these have happened). These problems cause both inefficiencies in how quickly and effectively GatsbyJS evolves and also emotional pain for contributors and maintainers. 
- Example of inefficiency problem: I have seen dozens of duplicate issues appear, which makes it hard to prioritize things and takes time to clean up.
- Example of emotional pain problem: In rare occasions, we've lost contributors who were angry and hurt about their issue or PR being forgotten or stalled without a definitive answer to whether it would be accepted or closed.

Additional research is in [this doc](https://docs.google.com/document/d/1WX88fb-rkK41lKx6yTr3tyfsmMhO8CYTbIiwfvGYPDo/edit#heading=h.a5wmxx733www).
</details>

## Goals

_What are the top 3 goals you want to accomplish with this epic? All goals should be specific, measurable, actionable, realistic, and timebound._

1. Decrease time to initial response
	- 75th percentile: ~24 hours
	- 90th percentile: ~72 hours
2. ~~Reduce mean time to resolution~~
	- Too hard to track; may incentivize the wrong things
	- Maybe a stretch goal, but would require some kind of quality metric
	- Would need to be grouped by issue type (e.g bug reports, maintenance tasks)
3. Produce a [cumulative flow diagram](https://kanbantool.com/cumulative-flow-diagram)
	- Needs:
		- Onboarding materials
		- Easy reference guide
		- High visibility (see above two points)

### Stretch Goals

1. Attach PRs to issues they close https://github.com/gatsbyjs/peril-gatsbyjs/issues/17
2. Auto-apply "WIP" label if title contains WIP https://github.com/gatsbyjs/gatsby/issues/7390
    - Probably not needed. See [this filter](https://github.com/gatsbyjs/gatsby/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+WIP+in%3Atitle)

### How will we know this epic is a success?

_What changes must we see, or what must be created for us to know the project was a success. How will we know when the project is done? How will we measure success?_

- Someone with no familiarity with the repo or Gatsby in general could follow our checklist/flow chart to put new issues into the right channels.
	- This will start as a flow chart that @marisamorby will create in Whimsical.
- Contributors don't need to install ZenHub to manage issues for the repo.
- Contributors need to be able to quickly open filtered views of different issue buckets.
	- For example, first-time contributors should be able to see a link to all issues labeled with `good first issue`.
	- MVP is a page in the docs with links to various GitHub filtered views.
	- @jlengstorf will own this
- Additional documentation that clearly explains where to find all of the artifacts created in this issue, how to use them, and where to go for help.
	- @marisamorby 
- Initial automations are in place, tested, and working as expected.
	- @jlengstorf
- Core maintainers need a process to identify and label/update issues correctly for community discovery (in maintainer meetings).
	- Process is going to be handled by @marisamorby via interviewing core maintainers.

### What are the risks to the epic?

If we overengineer this solution, no one will follow it. A process no one follows isn't a solution.

If we fail to make the right thing the easy thing, we'll spend a bunch of time building this and see it abandoned immediately — or, worse, we'll see contributors leave because we made it too hard/confusing to contribute.

### What questions do we still need to answer, or what resources do we need?

_Is there research to be done? Are there things we don’t know? Are there documents we need access to? Is there contact info we need? Add those questions as bullet points here._

- [ ] How can we define a metric for issue completion quality? What does that mean, and how would we track it?
	- @marisamorby will take this on
- [ ] Can we track a contributor's maintenance activity for e.g. swag rewards?
- [ ] How do issues get bucketed?
	- Labels? ZenHub? Both?
	- Can Peril handle moving issues in ZenHub based on labels?
- [ ] What is the level of effort required for core maintainers to add appropriate context and label them so they're easy to find?
	- Where is the decision made?
	- Who makes it?
	- What is the criteria for an issue being written out vs. worked on?
		- Reviewed in OSS backlog grooming meetings
	- How does an issue get turned over to the community?
		- Labeling: status, level of effort, difficulty?
- [x] What should be automated during the first phase of this project?
	- Stalebot https://github.com/gatsbyjs/gatsby/issues/6784 and https://github.com/gatsbyjs/gatsby/issues/6785 and https://github.com/gatsbyjs/gatsby/issues/7257 and https://github.com/gatsbyjs/gatsby/issues/7258
	- YAML validation: https://github.com/gatsbyjs/gatsby/issues/6634
		- Blog author validation: https://github.com/gatsbyjs/peril-gatsbyjs/issues/29
		- Site showcase: https://github.com/gatsbyjs/gatsby/issues/6538
		- Sites vs starters: https://github.com/gatsbyjs/peril-gatsbyjs/issues/38
	- Bug issue validation: https://github.com/gatsbyjs/gatsby/issues/6783
		- Env info
		- Check link to a reproduction repo
	- Conventional commits format enformcement bot: https://github.com/gatsbyjs/peril-gatsbyjs/issues/39
		- Does this actually apply changelogs to the appropriate packages?
- [ ] Where will we track the things we learn as this process rolls out?
	- @marisamorby will put together a doc for tracking what we learn.
	- How do we ensure that docs are discoverable by the keywords we'd be looking for?

**Comment by marisamorby** [comment]
Adding information from Issue #7618 which has been closed out.

We need to also `define state machine // decision tree for issues w/ tags`.

This means that we need to think about the decision tree we will be using when we implement the OSS Process. The goal here is to be able to visualize where issues are, what state they're in, what's blocked, and how long they've been there. This will allow us to create an easy to use dashboard and automate where possible to cut down on manual checks.

**Comment by jlengstorf** [comment]
I did some sketching on this today to try and create preliminary flow charts. Posting them here for posterity, and to give anyone who'd like to weigh in the chance to provide feedback before we get too far down the dev path.

I've transcribed a lot of it as well, for easier quotes in discussion and better a11y.

## What are the biggest bottlenecks/time drains in OSS management?

![img_20180911_133438](https://user-images.githubusercontent.com/163561/45388300-64de1800-b5cd-11e8-8da2-b50024a08232.jpg)

1. PR reviews
2. Stale issues
3. Reproductions/bug verifications

## What is our PR review process?

![img_20180911_134759](https://user-images.githubusercontent.com/163561/45388319-78897e80-b5cd-11e8-948b-cc3e76a65598.jpg)

> **NOTE:** This is written as pseudo-code-ish flow charts. Please ask if this is confusing.

1. Did the tests pass?
	- Yes
		- Continue to step 2
	- No
		- Post a comment letting the author know
		- Label as `status: blocked`
		- Exit the flow
2. Is this PR from a first-time contributor?
	- Yes
		- Add the label `review first`
		- Continue to step 3
	- No
		- Continue to step 3
3. Is this PR small? (<= 20 lines changed)
	- Yes
		- Add the label `review first`
	- No
		- Post a comment with tips for:
			- Getting faster reviews by submitting smaller PRs
			- How to break large PRs into smaller ones
4. Assign the PR to its author
	- I forgot to add this in the original photo

## How do we handle stale issues?

![img_20180911_133448](https://user-images.githubusercontent.com/163561/45388308-69a2cc00-b5cd-11e8-9f7a-8b869d384f49.jpg)

### Daily check on all issues

1. Has it been >= 20 days since the issue was updated?
	- Yes
		- Continue to step 2
	- No
		- Take no action; exit the flow
2. Is there an open PR attached to this issue (using ZenHub's "connected issue" feature)?
	- Yes
		- Take no action; exit the flow
	- No
		- Continue to step 3
3. Is the issue labeled with `not stale`?
	- Yes
		- Take no action; exit the flow
	- No
		- Add the label `stale?`
		- Post a comment requesting additional info, asking the author to validate their bug against the latest versions of Gatsby, etc.

### Daily check on `stale?` issues

1. Has the issue been updated since the follow-up comment?
	- Yes
		- Remove the `stale?` label
		- Exit the flow
	- No
		- Continue to step 2
2. Has it been >= 10 days since the issue was updated?
	- Yes
		- Continue to step 3
	- No
		- Exit the flow
3. Is the issue labeled with `not stale`?
	- Yes
		- Exit the flow
	- No
		- Close the issue
		- Post a comment explaining why stale issues are closed and how to create a new issue later if necessary

## How do we validate bug issues?

![img_20180911_140730](https://user-images.githubusercontent.com/163561/45388344-8a6b2180-b5cd-11e8-8f7b-fccad3723d00.jpg)

On all new issues:

1. Was the bug template used to create this issue?
	- Yes
		- Continue to step 2
	- No
		- Do nothing; exit the flow
2. Is a reproduction link provided in the "please post a link to a reproduction" section?
	- Yes
		- Continue to step 3
	- No
		- Post a comment requesting a reproduction
		- Add the label `status: needs reproduction`
		- Continue to step 3
3. Is environment info posted?
	- Yes
		- Add the label `type: bug`
	- No
		- Post a comment requesting envinfo and explaining how to get it
		- Add the label `status: needs more info`
		- Add the label `type: bug`

**Comment by shannonbux** [comment]
I like these. Only question is actually how someone who isn't super
technical can report bugs (read: me!). I often do sort of QA testing and
don't really have links to a reproduction...Just steps to reproduce the
behavior...

Also, these charts, once finalized, I think could make really good printed
material. There are some things I just like to print and this would be one
of them.

**Comment by marisamorby** [comment]
@shannonbux: I think those are great questions!

Per the thing about printing these, I'll get these into flowcharts as the OSS Process keeps moving along. :)

**Comment by jlengstorf** [comment]
Things to be done:

- [ ] @jlengstorf to set up a weekly meeting
- [ ] @jlengstorf to merge all duplicate issues
- [ ] @marisamorby to set up an agenda for ongoing project tracking
- [ ] @jlengstorf and @marisamorby to create issues for the work we scoped out above
