### ISSUE TITLE
[EPIC] Community Experiments

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/gatsby#7613]
> **NOTE:** This issue is an epic, which bundles up lots of related issues into a single goal. If you have the [free ZenHub extension](https://www.zenhub.com/), you’ll be able to see overall progress and related issues, as well as a "board view" that shows this epic from a bird's-eye view.

### Who will own this?

Responsibility  | Contributor(s)
--------------- | ---------------------------------------------------------
AoR owner       | @jlengstorf
Domain owner    | TBD
Project manager | TBD
Tech lead       | TBD
Contributors    | @jlengstorf, @kkemple, @lindaleebumblebee, @marisamorby, @calcsam 

### Description

We want to try out some fun things to see how we can be even more engaged with the community. A few ideas we have now are:

- [ ] Inkstreaming (regular livestreaming of dev work, planning/kickoff meetings, and other company-building tasks)
- [ ] Collaboration with non-profits (e.g. limited run swag https://github.com/gatsbyjs/store.gatsbyjs.org/issues/52, partnering to build Gatsby sites with non-profits)
- [ ] Scale pair programming (see https://github.com/gatsbyjs/gatsby/issues/7610)
- [ ] Meetup-in-a-box (can we give a lot of materials, etc. to make running a Gatsby meetup super easy?)

### Goals

_What are the top 3 goals you want to accomplish with this epic? All goals should be specific, measurable, actionable, realistic, and timebound._

1. We want to demonstrate a commitment to low-cost experiments that make Gatsby better
2. We want to improve the experience for our community by offering additional opportunities to get involved
3. We want to encourage more people to join the Gatsby community

### How will we know this epic is a success?

_What changes must we see, or what must be created for us to know the project was a success. How will we know when the project is done? How will we measure success?_

- For each experiment, we want to see an increase in community engagement

### What are the risks to the epic?

_In a few sentences, describe what high-level questions we still need to answer about the project. How could this go wrong? What are the trade-offs? Do we need to close a door to go through this one?_

If we implement these experiments poorly, we'll get bad data about whether or not it worked. If we go overboard, we risk wasting time on ideas that aren't actually accomplishing anything.

### What questions do we still need to answer, or what resources do we need?

_Is there research to be done? Are there things we don’t know? Are there documents we need access to? Is there contact info we need? Add those questions as bullet points here._

- What other quick experiments would help the community?
- Should we run some research to get ideas?
