### ISSUE TITLE
[EPIC]Report test coverage on Pull Requests

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#7614]
### Who will own this?

**Area of Responsibility:**

_Select the Area of Responsibility *most impacted* by this Epic_

- [x] OSS

### Summary

Add test coverage reporting to Gatsby. Automatically report coverage on new Pull Requests. Investigate enforcing test coverage for new features.

### How will this impact Gatsby?

**Domains**

_List the impacted domains here_

**Components**

_List the impacted Components here_

### Goals

_What are the top 3 goals you want to accomplish with this epic? All goals should be specific, measurable, actionable, realistic, and timebound._

1.  
2.  
3.

### How will we know this epic is a success?

_What changes must we see, or what must be created for us to know the project was a success. How will we know when the project is done? How will we measure success?_

**User Can Statement**

- User can...

**Metrics to Measure Success**

- We will see an increase /decrease in...

### Additional Description

_In a few sentences, describe the current status of the epic, what we know, and what's already been done._

### What are the risks to the epic?

_In a few sentences, describe what high-level questions we still need to answer about the project. How could this go wrong? What are the trade-offs? Do we need to close a door to go through this one?_

### What questions do we still need to answer, or what resources do we need?

_Is there research to be done? Are there things we don’t know? Are there documents we need access to? Is there contact info we need? Add those questions as bullet points here._

### How will we complete the epic?

_What are the steps involved in taking this from idea through to reality?_

### How else could we accomplish the same goal?

_Are there other ways to accomplish the goals you listed above? How else could we do the same thing?_

## Next Steps
- [ ] Under `Pipeline` select `Proposed Epics` (only if you are NOT the AoR owner)
- [ ] Under `Assignees` select the `AoR Owner`you listed in the Epic 
- [ ] Under `Labels` select `Epic` 
- [ ] Select `Create Epic`
