### ISSUE TITLE
[EPIC] Improve reliability of Windows CI

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#7617]
### Who will own this?

_What Area of Responsibility does this fall into? Who will own the work, and who needs to be aware of the work?_

**Area of Responsibility:**

_Select the Area of Responsibility *most impacted* by this Epic_

- [x] OSS

### Summary

Gatsby uses a free Appveyor account to run Windows CI tests. The tests are very slow, and sometimes don't get reported at all. This means that PRs are often not tested on Windows before being merged in.

### How will this impact Gatsby?

**Domains**

_List the impacted domains here_

**Components**

_List the impacted Components here_

### Goals

_What are the top 3 goals you want to accomplish with this epic? All goals should be specific, measurable, actionable, realistic, and timebound._

1.  
2.  
3.

### How will we know this epic is a success?

_What changes must we see, or what must be created for us to know the project was a success. How will we know when the project is done? How will we measure success?_

**User Can Statement**

- User can...

**Metrics to Measure Success**

- We will see an increase /decrease in...

### Additional Description

_In a few sentences, describe the current status of the epic, what we know, and what's already been done._

### What are the risks to the epic?

_In a few sentences, describe what high-level questions we still need to answer about the project. How could this go wrong? What are the trade-offs? Do we need to close a door to go through this one?_

### What questions do we still need to answer, or what resources do we need?

_Is there research to be done? Are there things we don’t know? Are there documents we need access to? Is there contact info we need? Add those questions as bullet points here._

### How will we complete the epic?

_What are the steps involved in taking this from idea through to reality?_

### How else could we accomplish the same goal?

_Are there other ways to accomplish the goals you listed above? How else could we do the same thing?_

## Next Steps
- [ ] Under `Pipeline` select `Proposed Epics` (only if you are NOT the AoR owner)
- [ ] Under `Assignees` select the `AoR Owner`you listed in the Epic 
- [ ] Under `Labels` select `Epic` 
- [ ] Select `Create Epic`

**Comment by davidbailey00** [comment]
cc @m-allanson @KyleAMathews I've created #7652 which describes the two problems currently causing all Windows builds to fail. However, fixing these issues won't impact on the speed of Windows testing, so there might still be problems.

**Comment by m-allanson** [comment]
Great stuff, thanks @davidbailey00 👍 

Here's some WIP notes on improving AppVeyor build times, which should also help with reliability.

### Rolling builds

There's a "rolling builds" configuration setting for AppVeyor that will tell it to only test the newest commit from any given PR: https://www.appveyor.com/docs/build-configuration/#rolling-builds. This has to be enabled through the AppVeyor UI.

From the Appveyor docs:

>"rolling builds" are great for very active OSS projects with lengthy queue. Whenever you do a new commit to the same branch OR pull request all current queued/running builds for that branch or PR are cancelled and the new one is queued. Other words, rolling builds make sure that only the most recent commit is built.

I can't see this option in the AppVeyor UI, I assume @KyleAMathews needs to give @pieh and myself additional permissions on the AppVeyor account?

### Fail strategy

Appeyor's default behaviour is to run all build jobs even if one of them fails. There is a `fast_finish` option which will cancel all other jobs as soon as one job fails.

https://www.appveyor.com/docs/build-configuration/#failing-strategy

### Concurrent jobs

Appveyor offers one concurrent job for OSS builds. Additional concurrency can be added by paying for a basic account, and then paying $25/month per additional concurrent job: https://www.appveyor.com/pricing/

### Investigate caching 

Cache `node_modules` between builds? Cache anything else? 

https://www.appveyor.com/docs/build-cache/

### Job matrix configuration

There is an [install script that cancels most jobs in the matrix](https://github.com/gatsbyjs/gatsby/blob/46290c2b0e7894fca036bdcc658a5d1936c4221f/appveyor.yml#L49), running them only for releases or forced builds. However, this script does not run until after the repo has been cloned for each job, meaning they can take a couple of minutes to be cancelled. [See example](https://ci.appveyor.com/project/KyleAMathews/gatsby/build/1.0.9909).

Can this functionality be replicated via Appveyor's config options? [See config reference](https://www.appveyor.com/docs/appveyor-yml/).

An alternative would be to temporarily drop these extra jobs, and look at adding them back in once everything else here has been investigated. 

I assume these jobs don't run on every PR because they take a while - but it seems counterproductive to have tests that are only run under certain conditions. Maybe we should reduce the number of jobs in the matrix and always run them. Instead of having many jobs that are only run under certain conditions.

### Other things to investigate

- Enable `shallow_clone: true`? https://www.appveyor.com/docs/appveyor-yml/

**Comment by KyleAMathews** [comment]
Nice investigation @m-allanson! Stopping builds + paying for more concurrency seems like easy wins.

**Comment by m-allanson** [comment]
@KyleAMathews has enabled the rolling builds feature

**Comment by m-allanson** [comment]
This could be worth looking at: https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/

**Comment by jeremyepling** [comment]
I'm a product manager on Azure Pipelines. Let me know if you have any questions or suggestions.

**Comment by pieh** [comment]
@jeremyepling Sorry for getting back to You late, we just recently started experimenting with Azure Pipelines and right now we are facing git checkout CRLF/LF problem:
in https://github.com/gatsbyjs/gatsby/pull/8836 there is attempt to fix our unit tests for windows (which passes currently for appveyor CI but fails in our rudimentary Azure Pipelines setup) - snapshot don't match most likely because saved snapshot are checked out with CRLF style line endings (as opposed to LF style line endings that function we tests produce). Is there option to set Azure Pipelines checkout to use LF line endings?

I saw there is `checkout` configuration, but it doesn't seem to cover that part - https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts#checkout

**Comment by pieh** [comment]
Seems like we can use `.gitattributes` to handle CRLF/LF issues - https://github.com/gatsbyjs/gatsby/pull/8922 :)

**Comment by jeremyepling** [comment]
I got a [successful build](https://dev.azure.com/jeremyepling/gatsby/_build/results?buildId=36&view=logs) after I created a [.gitattributes file](https://gist.github.com/jeremyepling/e727f0d9d94a2ef6267c9942beeb780f) that [sets all line endings to LF for your repository](https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings). This file will override Git user settings for CRLF.

I'd like to have a way to specify gitconfig values from the Azure Pipelines YAML, but we don't have that yet.

**Comment by jeremyepling** [comment]
I should have refreshed the page earlier. I'm just now seeing your comment. :)
