### ISSUE TITLE
[EPIC] Test critical APIs

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#7620]
### Who will own this?

_What Area of Responsibility does this fall into? Who will own the work, and who needs to be aware of the work?_

**Area of Responsibility:**

- [x] OSS

### Summary

Identify critical untested areas of Gatsby and add testing for them to improve the reliability of Gatsby.

### How will this impact Gatsby?

**Domains**

_List the impacted domains here_

**Components**

_List the impacted Components here_

### Goals

_What are the top 3 goals you want to accomplish with this epic? All goals should be specific, measurable, actionable, realistic, and timebound._

1.  
2.  
3.

### How will we know this epic is a success?

_What changes must we see, or what must be created for us to know the project was a success. How will we know when the project is done? How will we measure success?_

**User Can Statement**

- User can...

**Metrics to Measure Success**

- We will see an increase /decrease in...

### Additional Description

_In a few sentences, describe the current status of the epic, what we know, and what's already been done._

### What are the risks to the epic?

_In a few sentences, describe what high-level questions we still need to answer about the project. How could this go wrong? What are the trade-offs? Do we need to close a door to go through this one?_

### What questions do we still need to answer, or what resources do we need?

_Is there research to be done? Are there things we don’t know? Are there documents we need access to? Is there contact info we need? Add those questions as bullet points here._

### How will we complete the epic?

_What are the steps involved in taking this from idea through to reality?_

### How else could we accomplish the same goal?

_Are there other ways to accomplish the goals you listed above? How else could we do the same thing?_

## Next Steps
- [ ] Under `Pipeline` select `Proposed Epics` (only if you are NOT the AoR owner)
- [ ] Under `Assignees` select the `AoR Owner`you listed in the Epic 
- [ ] Under `Labels` select `Epic` 
- [ ] Select `Create Epic`

**Comment by cpboyd** [comment]
I'd like to draw attention to bugs already reported in #7568 and #7564 regarding `wrapRootElement` and `wrapPageElement`.

I'm going to work on a PR for those.

**Comment by cpboyd** [comment]
Ok... So the issue is kind of complex because of how these two APIs replaced very different APIs in an attempt to standardize them across both `gatsby-ssr.js` and `gatsby-browser.js`.

I applaud @pieh's attempt to unify the different APIs.  I agree that given differences in [gatsby-plugin-jss](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-jss/src/) it seems like maybe there should probably be the possibility for different implementations depending on `develop` or `build` mode.

The difficulty is:
In `build` mode, the **ssr** versions of both is applied in the `build-html` stage [static-entry.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/static-entry.js) (which seems to make sense as these would be HTML changes).

While the **browser** versions are applied in both the `build-javascript` and `develop` stages.

Ultimately, the easiest solution would probably be to just put them both in the **browser** version and eliminate the **ssr** versions to reduce confusion.

I just don't know yet how that'd impact #6127 which brought about these changes to begin with.

**Comment by cpboyd** [comment]
@KyleAMathews Really, it ultimately boiled down to #7716.

I've been meaning to see if I can help add to the docs the stuff I've learned about the new APIs, but I've been busy with other things.
