### ISSUE TITLE
Content migration overview issue

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#8103]
## Summary

Lots of content in our blog, plugin and starter READmes, and other external resources have valuable content we could pull into the docs.

1. If you'd like to write one of these docs, pick one from the list below
2. Then click on this URL to check what existing content can be repurposed in the article you're writing: https://airtable.com/shrU9erBeq1lhDy1Z
4. Then, open a PR with your article and mention this Issue #8103 in the PR description!

Note -- These docs may be in one of three states:
1. No doc exists yet (no corresponding file/page exists)
2. A stub article exists (the file is created and needs to be filled out)
3. A doc exists, but there is additional content we've identified that could possibly be used to make it better.

### Sourcing
- [x] Sourcing from Netlify CMS
- [x] Sourcing from Drupal* #8740
- [x] Sourcing from WordPress* #8742
- [x] Sourcing from Contentful* #8741 
- [x] Sourcing from the filesystem* #8730

### Deploying
- [x] Deploying to S3/Cloudfront
- [x] Deploying to Netlify
- [x] Deploying to Aerobatic #8736
- [x] Deploying to Heroku #8721 (PR)
- [x] Deploying to Now #8737
- [x] Deploying to GitLab Pages #8738

### Hosting
- [x] Deploying & Hosting (overview)
- [x] Hosting on Netlify #8844 

### Styling
- [x] CSS Modules*
- [x] Component CSS* #8726
- [x] Creating global styles
- [x] Typography.js*
- [x] PostCSS* #8839

### Building pages
~~Building a page with a GraphQL query~~ ([Duplicative. Already exists](https://www.gatsbyjs.org/docs/page-query/))
~~Rendering sidebar navigation dynamically~~ (New doc, not migration)
- [x] Creating and modifying pages
- [x] Creating slugs for pages* #8727
- [x] Layout components #8845
- [ ] Programmatically create pages from data* #8841 (PR 
under review)

### Performance + Optimization
- [x] using gatsby-image to prevent image bloat
- [x] Progressive web app (PWA)
- [x] Performance (overview)
- [x] Lighthouse audit*
- [x] Caching
- [x] Using Service Workers With Gatsby #8849 
- [ ] Optimizing plugins with Guess.js* #8846 (PR in progess)
~~Optimizations that Gatsby makes for you (**hold, needs clarification; missing in airtable**)~~

### Overviews
~~How Gatsby Works Diagram (**hold, needs clarification; missing link in airtable**)~~

### Plugins
- [x] Plugins (overview) #7229 (PR)

### Headless CMS
- [X] Headless CMS (overview) #7292 (PR)

GraphQL
- [x] Introducing GraphiQL*
- [x] Querying data with GraphQL (overview)

### Process
~~How to submit a PR*~~
- [x] RFC process*
- [x] v1 release notes*
- [x] Submit to Plugin Library #8843
- [x] Project Structure: Repos, Folders, File Naming Conventions (closed in #8405)
- [ ] How to run a Gatsby workshop* #8847 
~~How to pitch Gatsby* (**hold, needs clarification; missing in airtable**)~~

### Testing
~~[ ] Test configuration with Gatsby (**hold, needs clarification; not scoped narrowly enough, all external sources**)~~

### Misc
~~Interactive pages* #8739~~
- [x] Commands (Gatsby CLI)*
- [x] Gatsby + markdown (doc)
- [x] How Gatsby works with GitHub pages
- [x] Adding search
- [x] Linking between pages* #8626 (PR)
- [x] Using Fragments #8834
- [x] Making a site with user authentication* #9179 (PR in progress)
- [ ] Gatsby i18n #8716 
- [x] Static folder* #9222 
- [ ] gatsby-source-filesystem programmatic import*
- [ ] Importing single files* (**hold, needs clarification; AR: imo, the identified content makes more sense on the page it's on**)
- [ ] Dropping images into static folders* (**hold, needs clarification; not sure this is distinct enough from "static folder" to warrant separation**)
- [ ] Importing media content* (**hold, needs clarification; not scoped narrowly enough, all external sources**)

### Motivation

We are doing this to bring valuable content into the docs so that it is more centralized, maintainable, and discoverable.

**Comment by shannonbux** [comment]
@calcsam

**Comment by didacta** [comment]
### Deploying to S3/Cloudfront
  ![Deploying to S3/Cloudfront](https://www.gatsbyjs.org/static/gatsbyaws-edb4966c5558dff09d460535dd28263d-00eda.jpeg)

In this post, we’ll walk through how to host & publish your next Gatsby
site to AWS using [AWS Amplify](https://aws-amplify.github.io/).

AWS Amplify is a combination of client library, CLI toolchain, and UI
components. Amplify allow developers to get up & running with full-stack
cloud-powered applications with features like authentication, GraphQL,
storage, REST APIs, analytics, Lambda functions, hosting & more.

Using the **Hosting** feature, you can deploy your application to AWS as
well as set up your site with Amazon Cloudfront CDN. This is what we’ll
be doing in this tutorial. Let’s begin\!

## [](#getting-started-gatsby)Getting Started - Gatsby

First, we’ll want to create a new Gatsby project. If you don’t already
have Gatsby installed, install it:

<div class="gatsby-highlight" data-language="sh">

```language-sh
npm install - global gatsby-cli
```

</div>

Next, we’ll create a new Gatsby site:

<div class="gatsby-highlight" data-language="sh">

```language-sh
gatsby new my-gatsby-site
```

</div>

Finally, change into the new site directory:

<div class="gatsby-highlight" data-language="sh">

```language-sh
cd my-gatsby-site
```

</div>

## [](#getting-started-aws-amplify)Getting Started - AWS Amplify

Now that we have our Gatsby site up & running, let’s add hosting & make
the site live on AWS.

First, we’ll install the AWS Amplify CLI:

<div class="gatsby-highlight" data-language="sh">

```language-sh
npm i -g @aws-amplify/cli
```

</div>

With the AWS Amplify CLI installed, we now need to configure it with an
IAM User:

<div class="gatsby-highlight" data-l="">

</div>

```
amplify configure
```

> For a video walkthrough of how to configure the AWS Amplify CLI, click here.

Now, we can create a new Amplify project in the root of our Gatsby project:

```
amplify init
```

- Choose your default editor: (for me, this is Visual Studio Code)
- Please choose the type of app that you’re building: javascript
- What JavaScript framework are you using: react
- Source Directory Path: src
- Distribution Directory Path: public
- Build Command: npm run-script build
- Start Command: npm run-script develop
- Do you want to use an AWS profile? Y
- Please choose the profile you want to use: default

Now, the Amplify project has been created. You will see that you have a new amplify folder in your project directory as well as an .amplifyrc file. Both of these contain your AWS Amplify project configuration.

Next, we can type amplify into our command line & see all of the options that we have:

```
amplify
```

At the bottom, we can see the available categories available to us. Hosting is the category we would like to enable, so let’s do so now:

```
amplify add hosting
```

Here, we'll be prompted for the following:

- Select the environment setup: **DEV**
  -hosting bucket name: **gatsbyproj-20180808112129-hosting-bucket (or type whatever you’d like the bucket name to be)**

This will set up our local project with everything we need, now we can publish the app to AWS. To do so, we’ll run the following command:

```
amplify publish
```

Here, we’ll be prompted for the following:

- Are you sure you want to continue? **Y**

Now, our resources will be pushed up to our account & our site will be published to a live url!

What just happened? A few things:

1.  Amplify runs npm run build to build a new distribution of your app
2.  A new S3 bucket is created in your AWS account
3. All code in the public directory is uploaded to the S3 bucket

We should have also be given the URL that the site is hosted on. At any time that we would like to get the url for our site, we can run:

```
amplify status
```
This command should give us all of the info about our app including the url of our website.

If we ever want to configure the hosting setup, including adding Cloudfront, we can run:
```
amplify configure hosting
```
Here, we’ll be prompted for what we would like to change about the project configuration.

> To learn more about AWS Amplify, check out the Getting Started page.

**Comment by shannonbux** [comment]
Hi @didacta! Would you mind opening a PR and mentioned this issue #8103 in the PR description to add the doc you added above?

**Comment by cardiv** [comment]
Oops, sorry. Checked _How Gatsby Changes Teams' Website Development Workflow_ accidentally. Removed it again. Before someone gets crazy about my edit. 😆

**Comment by OrthoDex** [comment]
Hi @shannonbux! I'll make a PR for the [Deploying to Heroku](https://www.gatsbyjs.org/docs/deploy-gatsby/#heroku) doc.

**Comment by jkjustjoshing** [comment]
I'm working on the "Using Fragments" section, should have a PR in the next 24-36 hours.

**Comment by dougajmcdonald** [comment]
I'd like to write a guide on deploying from Github, via Wercker to Azure if you'd be interested in having it added to the docs

**Comment by shannonbux** [comment]
great @jkjustjoshing that'd be great! Want to mention this issue in your PR for easy tracking?

Also @dougajmcdonald would you be interested in writing a blogpost on that? We trying to keep the number of deployment docs to just a select few, and then blog about other deployment strategies (and link to those blogposts from the deployment overview doc (/docs/deploying-and-hosting/)

**Comment by CanRau** [comment]
Brand guidelines/press kit page (https://github.com/gatsbyjs/gatsby/issues/4150) could maybe go on the list, too?

**Comment by dougajmcdonald** [comment]
@shannonbux I'd love to, do you have an oss Gatsby blog I can contribute to? Or do you want me to do something external?

**Comment by amberleyromo** [comment]
@dougajmcdonald we do! See this directory for blog content, and model your post in the same fashion: https://github.com/gatsbyjs/gatsby/tree/master/docs/blog

**Comment by amberleyromo** [comment]
@CanRau good thought. I think not here, because this issue is for content migration (@shannonbux has identified source material that could be helpful/repurposed into documentation). #4150 is possible/probable future content, but not something we have existing content to migrate.
