### ISSUE TITLE
[EPIC] v2.0 .org redesign (Docs landing page)

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#8769]
### Who will own this?

**Area of Responsibility:**

- [ ] Admin
- [ ] Cloud
- [ ] Customer Success
- [ ] Dashboard
- [ ] Developer Relations
- [ ] OSS
- [x] Learning
- [ ] Marketing
- [ ] Sales

Responsibility  | Contributor(s)
--------------- | ---------------------------------------------------------
AoR owner       | @shannonbux
Domain owner    | @name
Project manager | @name
Tech lead       | @name
Contributors    | @name

### Summary

We want to make room for www.gatsbyjs.org to grow. We're going to create a landing page for these items that need room and call them "Docs" in the top nav bar:
* Quick Start
* Guides
* API reference
* Tutorial
* Advanced Tutorials
* more... :) @fk will get this joke

### How will this impact Gatsby?

**Domains**

Primary: gatsbyjs.org
Secondary: .org docs

**Components**

_List the impacted Components here_

### Goals

1. increase the number of page views for docs
2. increase the number of contributions to docs

### How will we know this epic is a success?

This project is successful once the user can statements below are true.

**User Can Statement**

User can...
- [ ] find each docs item (listed in summary above) from the .org homepage
- [ ] continue to find each docs item through google search
- [ ] continue to be able to bookmark and share each docs item

**Metrics to Measure Success**

- Same as goals above

### Additional Description

@fk has developed designs in  https://github.com/gatsbyjs/gatsby/issues/7544#issuecomment-415726009

And has sketched out the pros of the second solution:

1. Priority nav plus More button with drop-down menu
2. Reduce nav items to 5, reorganize them and create landing pages

![bild von ios hochgeladen](https://user-images.githubusercontent.com/32467162/44824461-e0e66200-abc2-11e8-8c6d-cb3cd0668008.jpg)

### What are the risks to the epic?

- We could make pages harder to find
- We could lose people who like the current navigation

### What questions do we still need to answer, or what resources do we need?

* How much planning future .org changes are required in order to not go down the wrong road?

### How will we complete the epic?

We will complete the issues as they are assigned below this Epic.

### How else could we accomplish the same goal?

We could go with @fk's first option:
1. Priority nav plus More button with drop-down menu
