### ISSUE TITLE
[EPIC] v3.0 .org redesign (Community page)

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#8770]
### Who will own this?

**Area of Responsibility:**

- [ ] Admin
- [ ] Cloud
- [ ] Customer Success
- [ ] Dashboard
- [ ] Developer Relations
- [ ] OSS
- [x] Ecosystem
- [ ] Learning
- [ ] Marketing
- [ ] Sales

Responsibility  | Contributor(s)
--------------- | ---------------------------------------------------------
AoR owner       | @amberleyromo 
Domain owner    | @KyleAMathews 
Project manager | @name
Tech lead       | @name
Contributors    | @fk 

### Summary

We want to make room for www.gatsbyjs.org to grow. We're going to create a landing page for these items that need room and call them "Community" in the top nav bar:
* Code of Conduct
* How to Contribute
* SWAG (is this where it fits?)
* How to Connect (Gatsby Days and other meetups)

### How will this impact Gatsby?

**Domains**

gatsbyjs.org

**Components**

_List the impacted Components here_

### Goals

1. increase the number of page views to gatsbyjs.org 
2. increase the number of contributions to gatsbyjs.org
3. increase how much people use Gatsby to build sites

### How will we know this epic is a success?

This project is successful once the user can statements below are true.

**User Can Statement**

User can...
- [ ] find each community item from the homepage
- [ ] know how to contribute
- [ ] buy swag from the Gatsby store

**Metrics to Measure Success**

- Same as goals above

### Additional Description

@fk has developed designs in  https://github.com/gatsbyjs/gatsby/issues/7544#issuecomment-415726009

And has sketched out the pros of the second solution:

1. Priority nav plus More button with drop-down menu
2. Reduce nav items to 5, reorganize them and create landing pages

![bild von ios hochgeladen](https://user-images.githubusercontent.com/32467162/44824461-e0e66200-abc2-11e8-8c6d-cb3cd0668008.jpg)

### What are the risks to the epic?

- We could make pages harder to find
- We could lose people who like the current navigation

### What questions do we still need to answer, or what resources do we need?

* How much planning future .org changes are required in order to not go down the wrong road?

### How will we complete the epic?

We will complete the issues as they are assigned below this Epic.

### How else could we accomplish the same goal?

We could go with @fk's first option:
1. Priority nav plus More button with drop-down menu

**Comment by marisamorby** [comment]
@amberleyromo: This will be affected by the OSS Process Automation work in issue #9634 for OSS Dashboard Spec. We'll want to be sure to consider the OSS Process as we're building out this page.
