### ISSUE TITLE
[EPIC] .org redesign [homepage]

### ISSUE THREAD

**Issue by marisamorby** [gatsbyjs/gatsby#9456]
### Who will own this?

**Area of Responsibility:** Ecosystem

_Select the Area of Responsibility *most impacted* by this Epic and add it as a Label_

| Role                | Name  | RACI                                        |
| ------------------- | ----- | ------------------------------------------- |
| **AoR owner**       | @amberleyromo  | _Consulted about the epic_                  |
| **Domain owner**    | @KyleAMathews   | _Informed about epic_    |
| **Project manager** | @marisamorby  | _Responsible for setting epic tasks_        |
| **Tech lead**       | @amberleyromo  | _Accountable for setting guidelines for epic_                       |
| **Contributors**    | @amberleyromo @shannonbux @fk @marisamorby   | _Responsible for completing assigned tasks_ |

_**If you have questions about the Epic, start with the AoR Owner.**_

### Epic Description

We're in he process of redesigning gatsbyjs.org, and need to update the homepage along with the rest of the site

### How will this impact Gatsby?

**Products**

_List the impacted Products here_

**Components**

-Algolia search engine

### Goals

_What are the top 3 goals you want to accomplish with this epic? All goals should be specific, measurable, actionable, realistic, and timebound._

1.  2.  3.

### How will we know this epic is a success?

_What changes must we see, or what must be created for us to know the project was a success. How will we know when the project is done? How will we measure success?_

**Metrics to Measure Success**

- We will see an increase / decrease in...

### What are the risks to the epic?

_How could this go wrong? Are there trade-offs in doing this? Do we need to close a door to go through this one?_

### What questions do we still need to answer, or what resources do we need?

_Is there research to be done or things we don’t know? Are there documents we need access to? Is there contact info we need? Add those questions as bullet points here._

### How else could we accomplish the same goal?

_Are there other ways to accomplish the goals you listed above? How else could we do the same thing?_

## Next Steps

- [ ] Under `Pipeline` select `Proposed Epics` (only if you are NOT the AoR owner)
- [ ] Under `Assignees` select the `AoR Owner`you listed in the Epic
- [ ] Under `Labels` select `Epic`
- [ ] Under `Labels` select the appropriate `AoR`
- [ ] Select `Create Epic`

## You're all done!
